### ISSUE TITLE
分享文件提示该文件禁止分享

### ISSUE THREAD

**Issue by mlsub** [qjfoidnh/BaiduPCS-Go#1]
使用平台：树莓派4B
使用版本：arm64-v3.6.3
今天看到这里更新了就下载了编译好的版本测试了一下。上传和下载都没有问题，唯独分享功能似乎无法使用，使用`share set` 命令不管什么文件都提示`创建分享链接失败: 创建分享链接: 遇到错误, 远端服务器返回错误, 代码: 115, 消息: 该文件禁止分享` 但是在网页版百度网盘客户端却可以正常创建分享链接
请问是什么原因呢

**Comment by qjfoidnh** [comment]
已修复，已更新编译版本
