### ISSUE TITLE
上传文件失败，百度网盘有文件，显示0B

### ISSUE THREAD

**Issue by zzzop** [qjfoidnh/BaiduPCS-Go#101]
./BaiduPCS-Go upload BaiduPCS-Go .

[0] 提示: 当前上传单个文件最大并发量为: 4, 最大同时上传文件数为: 4
[1] 加入上传队列: BaiduPCS-Go
[1] 准备上传: BaiduPCS-Go
[1] 秒传失败, 开始上传文件...

[1] ↑ 10.06MB/10.06MB 831.96KB/s in 6s ............[1] 上传文件失败, 分片上传—合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31061, 消息: 文件已存在

上传结束, 时间: 7.579s, 总大小: 0B
以下文件上传失败: 
  1  /home/baidu/BaiduPCS-Go

**Comment by zzzop** [comment]
添加参数`--policy overwrite`可以上传，`newfile skip`都是相同的报错

**Comment by qjfoidnh** [comment]
最新版将同名文件处理策略放到了config里，config set -upload_policy=newcopy/overwrite/skip/fail，详情可参见config --help
download参数方式在未来会被废弃

**Comment by zzzop** [comment]
> 最新版将同名文件处理策略放到了config里，config set -upload_policy=newcopy/overwrite/skip/fail，详情可参见config --help
> download参数方式在未来会被废弃

有个问题我没表达清楚，网盘里没有文件的时候，直接上传就会显示有`文件已存在`这个错误提示

**Comment by qjfoidnh** [comment]
了解，应该是个bug，会修复一下

**Comment by qjfoidnh** [comment]
已修复，同时修复了newcopy策略会覆盖原文件的问题。另外skip策略实测与fail策略一致
