### ISSUE TITLE
上传文件提示文件已存在 错误代码31061

### ISSUE THREAD

**Issue by haobinnan** [qjfoidnh/BaiduPCS-Go#102]
[1] ↑ 10.00GB/10.00GB 4.71MB/s in 26m6s ............[1] 上传文件失败, 分片上传— 合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31061, 消息: 文件已存在

上传结束, 时间: 27m40.354s, 总大小: 0B
以下文件上传失败:
  1  /home/haobinnan/data/ProgramFiles/MyData_Temp/MyData.tar.gpg.00

**Comment by haobinnan** [comment]
以前正常啊

**Comment by haobinnan** [comment]
3.8.0正常 3.8.2 异常

**Comment by haobinnan** [comment]
我怀疑可能是 3.8.1 更正 上传增加同名文件自动跳过 时导致的。

**Comment by haobinnan** [comment]
我这个目录没有任何文件，但是别的目录中有此名文件（MyData.tar.gpg.00），我将能想到的信息都提供了。

**Comment by qjfoidnh** [comment]
嗯。。。前两天有个3.8.2是有bug的，存在了大概一天才换下去，现在用的是新下的么

**Comment by haobinnan** [comment]
我的3.8.2应该是之前几天下载的

**Comment by haobinnan** [comment]
这种情况 应该考虑新开 3.8.3

**Comment by qjfoidnh** [comment]
确实，这次偷懒了

**Comment by haobinnan** [comment]
哈哈，软件做的很好 我经常用，继续支持
