### ISSUE TITLE
最新的release压缩包全部解压失败

### ISSUE THREAD

**Issue by ghost** [qjfoidnh/BaiduPCS-Go#103]

**Comment by qjfoidnh** [comment]
复现到了，在Mac上会解压失败，win10好压正常，目前还没搞明白问题出在哪，建议先到"Action"里下未压缩的二进制包
https://github.com/qjfoidnh/BaiduPCS-Go/actions/runs/1064629847

**Comment by ghost** [comment]
<img width="575" alt="截屏2021-07-30 15 22 43" src="https://user-images.githubusercontent.com/20164277/127616620-4ca2baf2-1225-48ed-b0e8-c884ddf3dac7.png">
提供一个命令行的截图

**Comment by jyuan15** [comment]
win10用winrar和7z都解压不出来，提示“找不到指定路径”

![2021-08-12_132226](https://user-images.githubusercontent.com/12642186/129142598-a6585a2c-3bda-4191-a564-20c88d00a40f.jpg)
![2021-08-12_132413](https://user-images.githubusercontent.com/12642186/129142603-f586f654-05b4-4152-acb5-cd1c7375fae1.jpg)

**Comment by PDxtXHd** [comment]
@qjfoidnh 这个是因为你最新版的release里的压缩包中有一个无后缀的文档，名字和同目录下的文件夹名字相同，解压出来那个文档之后就无法再创建一个同名文件夹了。类似这样：
![image](https://user-images.githubusercontent.com/54795848/129582856-7a77de5b-67f2-4a82-acfc-63d1dda001d3.png)

**Comment by mrdobejelly** [comment]
![2021-08-18_151901](https://user-images.githubusercontent.com/19746097/129855047-84fd7814-b35e-4e56-9d02-a19853c0870b.png)
![2021-08-18_151457](https://user-images.githubusercontent.com/19746097/129855087-e93c5b0d-b628-4f05-bc58-4b816b1142f2.png)
确实是有个同名无后缀的文件导致解压失败，不要解压那个文件就行了，单独选定文件夹解压。

**Comment by qjfoidnh** [comment]
修复了
