### ISSUE TITLE
请问怎么可以知道当前上传文件的进度？

### ISSUE THREAD

**Issue by ghost** [qjfoidnh/BaiduPCS-Go#104]
我的是大文件上传。30个G左右，一开始不断归0，还以为是失败重传了。后面猜是分片上传，
1.那请问我怎么可以知道当前上传到哪个文件了呢？
2.有什么办法可以提高上传速度呢？只有500多kb。换接口地址？

**Comment by qjfoidnh** [comment]
1. 我猜你问的是“上传到哪个分片”，这个还真看不到，而且实现起来应该会挺麻烦...另外归0不太正常，好像就是失败了，据之前的反馈传20G以上文件是有失败的状况（即便开分片），当然这块测试不多，可以发两张截图看看。
2. 换接口对国内用户提升不大，可以把上传线程数和并发数改高点，默认值挺低的

**Comment by ghost** [comment]
<img width="581" alt="截屏2021-07-30 16 07 02" src="https://user-images.githubusercontent.com/20164277/127622128-22dc7f65-6e9a-46d7-979d-1af44927a0e9.png">
多次归0重传。然后好几个小时才上传了几百M

**Comment by ghost** [comment]
而且这个进度好像还会倒退的？（注意图一和图二的时间点）
![image](https://user-images.githubusercontent.com/20164277/127622969-8b258e83-157c-4e73-8bce-4c6161006237.png)
![image](https://user-images.githubusercontent.com/20164277/127623030-6d510a8f-7bd8-444d-9ef9-aa1cf452c8e2.png)

**Comment by qjfoidnh** [comment]
多半是文件大小的问题，超20G的上传应该是无法成功的
要改一下readme了

**Comment by ghost** [comment]
有没有可能是进度那里计算出错了。可是分片上传的话，我现在远远没到20G呀

**Comment by qjfoidnh** [comment]
#68 类似的问题，不过那个有显式的报错还不一样。方便给上传出错的文件来个磁链啥的不，我本地复现一下

**Comment by ghost** [comment]
貌似没有磁力连接，但是有个迅雷云的连接，你需要不？
「链接：https://pan.xunlei.com/s/VMg3G9GR3NtiTEdeFNFvZEA6A1 提取码：r75w”复制这段内容后打开手机迅雷App，查看更方便」

**Comment by ghost** [comment]
我感觉应该是不断的重传分片，目前进度已经超过22G了
![截屏2021-08-02 08 28 09](https://user-images.githubusercontent.com/20164277/127790319-5a45c412-65ed-43aa-a0c8-aadc4d2d8b7f.png)

**Comment by ghost** [comment]
update:
30G已经上传成功了,大概花了100个小时。按照正常速度应该20多个小时就能搞定的了。但是好像在不断的重传分片，而且感觉如果中断之后，再次上传好像会更快一点
感谢作者的工具！

**Comment by ghost** [comment]
[nohup.txt](https://github.com/qjfoidnh/BaiduPCS-Go/files/6935070/nohup.txt)
提供一个日志文件，是重启电脑之后，再次上传的记录
