### ISSUE TITLE
新功能建议：突破非会员转存数量限制

### ISSUE THREAD

**Issue by NEPDream** [qjfoidnh/BaiduPCS-Go#105]
百度非会员，会限制一次性转存的文件数量，我有一个建议，如果可以获取到需要转存的文件的数量，可以智能地按照深度遍历的方式，一点点的在限制内，把所有文件转存完毕。

**Comment by qjfoidnh** [comment]
这个功能很早以前预想过，现在代码里甚至还能找到残留的开发痕迹，主要是写着写着发现还挺麻烦就没搞了，次要原因是规避一些法律风险
