### ISSUE TITLE
请问 通过分享链接下载的命令是什么

### ISSUE THREAD

**Issue by wdgitzh** [qjfoidnh/BaiduPCS-Go#11]
通过分享链接下载的命令是什么

**Comment by qjfoidnh** [comment]
目前还不支持直接通过分享链接下载，可以用shell脚本分别调用转存和下载命令实现（转存成功会返回文件名）

**Comment by wdgitzh** [comment]
可能我没表述清楚
把文件分享后，再下载
原来使用过，后来忘记了命令

**Comment by qjfoidnh** [comment]
在ikkira的早期版本里可以在下载时通过-mode=share指定，2020年4月的更新中取消掉了，只保留了location, pcs模式。
