### ISSUE TITLE
文件路径含有非法字符，已跳过!

### ISSUE THREAD

**Issue by 10362227** [qjfoidnh/BaiduPCS-Go#111]
BaiduPCS-Go upload "H:/Temp/115百度云/" "/12345"

H:/Temp/115百度云/Macy Gray ft Nik West - Stop, Drop, Roll.mp4 文件路径含有非法字符，已跳过!
H:/Temp/115百度云/Shaggy - It Wasn't Me (ft. RikRok) (ntsc_cda_MDL&DA).vob 文件路径含有非法字符，已跳过!
.
.
.

一堆这样的，似乎是出现了逗号、单引号这类字符引起的，我用的另一版本（3.7.0.0 liuzhuoling）没有这种问题

**Comment by qjfoidnh** [comment]
单引号等符号在某些情景下会触发非法字符引起不必要的麻烦，在某次更新中禁止了这类文件名的使用

**Comment by snje1987** [comment]
有些加密软件加密后的文件，比如[encfs](https://github.com/vgough/encfs)，会产生包含英文逗号的文件名，所以最好还是不要直接禁止使用，如果可以做成配置项的话会比较好。这只是一个建议，如果没时间的话可以不用考虑。
