### ISSUE TITLE
【非技术疑问】本客户端会导致黑号吗？

### ISSUE THREAD

**Issue by 1c383r9** [qjfoidnh/BaiduPCS-Go#116]
很久没用百度云了，前几天开了个会员用IDM下了一下子然后秒黑（其实没速度，下不动），然后怕了··

近期想开个新svip在路由上用本客户端下些大文档，60多G，不知道会不会黑号？

只是新用户疑问， 没有任何引战\贬低，期待回复。（抱歉滥用issues，其实开放discussion区还是很不错的）

谢谢！

**Comment by pongfcnkl** [comment]
会

**Comment by qjfoidnh** [comment]
我自己基本每天都会拿它下东西，SVIP会员的话只要按着推荐的线程数设置，至少我个人这儿是没遇到过小黑屋的

IDM秒黑我猜跟过大线程数或者错误的浏览器头有关系

**Comment by 1c383r9** [comment]
> 我自己基本每天都会拿它下东西，SVIP会员的话只要按着推荐的线程数设置，至少我个人这儿是没遇到过小黑屋的
> 
> IDM秒黑我猜跟过大线程数或者错误的浏览器头有关系

谢谢解答。
