### ISSUE TITLE
--nosplit 禁用分片 上传文件有进度回滚的问题

### ISSUE THREAD

**Issue by mengzonefire** [qjfoidnh/BaiduPCS-Go#117]
如题, 1G以上的文件很容易反复触发, 很难成功上传

**Comment by qjfoidnh** [comment]
现在不分片上传的逻辑就是把整个文件作为一个大分片，暂时没想到什么改进方法。可以试试把同时上传文件数和线程数设为1，模拟一种假的“单分片”（实际还是分片了，只不过没了并发）

**Comment by mengzonefire** [comment]
好吧, 测试了下用原先的旧版非分片上传接口 d.pcs.baidu.com/rest/2.0/pcs/file?method=upload

也是每次传个200M左右就返回http500, 那看来就是百度服务器的问题了, 确实无能为力
