### ISSUE TITLE
从昨天开始svip账号下载好像限速了，是我自身的问题还是官方升级了？

### ISSUE THREAD

**Issue by monkey0416** [qjfoidnh/BaiduPCS-Go#119]
svip账号，官网客户端下载速度提速正常。用baidupcs-go下载被限制在1m/s之内。
是官方升级了还是我个人的问题？其他人有碰到吗

**Comment by hythzx** [comment]
我也是同样的问题，稳定在200-300kb，之前都是10m以上的

**Comment by hythzx** [comment]
@monkey0416 我把下载并发数提高了，下载又正常了

**Comment by pongfcnkl** [comment]
是Windows系统？在前面加个--verbose参数看看下载域名是不是qdall01开头的？

**Comment by Elypha** [comment]
我这边看到的有两个下载域名
```
yqct02.baidupcs.com
yqall01.baidupcs.com
```
启动的瞬间有正常速度，随后80%的时间速度为0，其余时间100kb/s~5mb/s不等

**Comment by monkey0416** [comment]
> 是Windows系统？在前面加个--verbose参数看看下载域名是不是qdall01开头的？

mac和centos，-verbose 这个怎么加 download 命令没有这个参数吧

**Comment by monkey0416** [comment]
获取直链这三个开头
 https://yqct02.baidupcs.com
https://yqall01.baidupcs.com
https://allall02.baidupcs.com

**Comment by walke2019** [comment]
存在一样的问题，用的linux系统，是不是下载被百度直接限速了？？

**Comment by qjfoidnh** [comment]
应该不是个别问题，推测官方换了接口。最近比较忙没空逆向啦，大家对付一天是一天吧~

**Comment by qjfoidnh** [comment]
哦我想多了，换个user-agent就恢复满速了

请按如下操作：
进入程序后，config set -pan_ua="新的UA"
UA举例：
netdisk;P2SP;2.2.90.43;WindowsBaiduYunGuanJia;netdisk;11.4.5;android-android;11.0;JSbridge4.4.0;LogStatistic
netdisk;P2SP;3.0.0.3;netdisk;11.5.3;PC;PC-Windows;android-android;11.0;JSbridge4.4.0
netdisk;P2SP;2.2.91.26;netdisk;11.6.3;GALAXY_S8;android-android;7.0;JSbridge4.4.0;jointBridge;1.1.0;
推荐自己构造UA，比如更换一下手机型号，安卓版本号等

**Comment by monkey0416** [comment]
可以了，谢谢。

**Comment by walke2019** [comment]
通过换agent和UA已解决

**Comment by buzhangjiuzhou** [comment]
换UA有效果！

**Comment by wzrzt** [comment]
> 通过换agent和UA已解决

请问是user-agent, pan_ua都更换了吗，有没有构造规则。我复制了前面举例的pan_ua最后一个，手机型号改成了GALAXY_S20+，没啥变化，速度是2秒几百kb，再几秒0，循环，整体很慢

**Comment by buzhangjiuzhou** [comment]
> > 通过换agent和UA已解决
> 
> 请问是user-agent, pan_ua都更换了吗，有没有构造规则。我复制了前面举例的pan_ua最后一个，手机型号改成了GALAXY_S20+，没啥变化，速度是2秒几百kb，再几秒0，循环，整体很慢

我把user-agent换成netdisk;P2SP;3.0.0.3;netdisk;11.5.3;PC;PC-Windows;android-android;11.0;JSbridge4.4.0，之后就好了。

**Comment by wzrzt** [comment]
> > > 通过换agent和UA已解决
> > 
> > 
> > 请问是user-agent, pan_ua都更换了吗，有没有构造规则。我复制了前面举例的pan_ua最后一个，手机型号改成了GALAXY_S20+，没啥变化，速度是2秒几百kb，再几秒0，循环，整体很慢
> 
> 我把user-agent换成netdisk;P2SP;3.0.0.3;netdisk;11.5.3;PC;PC-Windows;android-android;11.0;JSbridge4.4.0，之后就好了。

感谢，我试试

**Comment by sddzcuigc** [comment]
为什么我换了UA也只有5M/s，而利用pandownload是24M/s

**Comment by qjfoidnh** [comment]
可以检查下下载线程数，svip开到10+比较合适

**Comment by qiuwei** [comment]
我怎么改了UA后还是同样的现象。 三个UA都试过了。
## edit 
更新到最新版本后正常了。

**Comment by haobinnan** [comment]
> 哦我想多了，换个user-agent就恢复满速了
> 
> 请按如下操作：
> 进入程序后，config set -pan_ua="新的UA"
> UA举例：
> netdisk;P2SP;2.2.90.43;WindowsBaiduYunGuanJia;netdisk;11.4.5;android-android;11.0;JSbridge4.4.0;LogStatistic
> netdisk;P2SP;3.0.0.3;netdisk;11.5.3;PC;PC-Windows;android-android;11.0;JSbridge4.4.0
> netdisk;P2SP;2.2.91.26;netdisk;11.6.3;GALAXY_S8;android-android;7.0;JSbridge4.4.0;jointBridge;1.1.0;
> 推荐自己构造UA，比如更换一下手机型号，安卓版本号等

的确可以了，为什么会这样？
