### ISSUE TITLE
可以多文件同时上传吗？

### ISSUE THREAD

**Issue by jiangjiangflies** [qjfoidnh/BaiduPCS-Go#12]
我有很多个文件，可以多进程同时上传多个文件吗？单个文件上传太慢了，

**Comment by qjfoidnh** [comment]
已更新3.7.1版本支持该特性

注意总上传线程数是max_upload_load和max_upload_parallel的乘积

**Comment by jiangjiangflies** [comment]
> 已更新3.7.1版本支持该特性
> 
> 注意总上传线程数是max_upload_load和max_upload_parallel的乘积

谢谢！请问多文件上传的参数具体如何设置？刚看上传文件命令的wiki里没有提到哦

**Comment by qjfoidnh** [comment]
> > 已更新3.7.1版本支持该特性
> > 注意总上传线程数是max_upload_load和max_upload_parallel的乘积
> 
> 谢谢！请问多文件上传的参数具体如何设置？刚看上传文件命令的wiki里没有提到哦

可在程序内用config命令查看默认值及相关说明。

**Comment by jiangjiangflies** [comment]
谢谢大佬！我看目前最多同时上传4个文件。能不能提高一下上限？我想同时上传20个左右，类似rclone --transfers参数，可以根据调比较大，跑满带宽。 我的度盘买的SVIP，同时上传多文件应该不会被封。

**Comment by qjfoidnh** [comment]
> 谢谢大佬！我看目前最多同时上传4个文件。能不能提高一下上限？我想同时上传20个左右，类似rclone --transfers参数，可以根据调比较大，跑满带宽。 我的度盘买的SVIP，同时上传多文件应该不会被封。

没有上限，可以自行设置，config里给出的范围只是建议值；另外upload命令里也支持单次指定，具体可参加upload --help

**Comment by jiangjiangflies** [comment]
可以，很强！支持大佬！
