### ISSUE TITLE
v3.8.2 tarball checksum changed?

### ISSUE THREAD

**Issue by carlocab** [qjfoidnh/BaiduPCS-Go#120]
We're attempting to update Homebrew's version of Go at Homebrew/homebrew-core#83413.

While testing the new version, CI produced the following error:
```
==> brew install --build-from-source baidupcs-go
==> FAILED
==> Downloading https://github.com/qjfoidnh/BaiduPCS-Go/archive/v3.8.2.tar.gz
==> Downloading from https://codeload.github.com/qjfoidnh/BaiduPCS-Go/tar.gz/v3.8.2
Error: SHA256 mismatch
Expected: 3f6c95b82a769fb7c947a181d8f57ae60344acabba0a27a33249b9abbf365601
  Actual: 65d5482bc2a82cb244b978b8e1369bd5b1c429afce74651e5aea28e057a78ae3
```

I can update the sha256 associated with BaiduPCS-GO, but CI will come back to me with the following error:
```
baidupcs-go:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

Can I confirm that the change in checksum was intentional? Thanks.

**Comment by carlocab** [comment]
This seems to have been addressed in #102, but it'd help to get confirmation in case I did Google Translate wrong 🙂

**Comment by j178** [comment]
Yes, you're right, the owner replaced the `3.8.2` with a new package.

**Comment by carlocab** [comment]
Thanks! Was there a problem with the original version of `3.8.2`? i.e. should users who installed the earlier one update to the newer one?

**Comment by qjfoidnh** [comment]
It's about a serious bug in upload function, so update, I suggest.

**Comment by carlocab** [comment]
Ok, thanks again!

By the way, it'd be very helpful for your downstream package managers for you to not re-publish tags after they've already been released. Bug fixes should ideally be reflected by a new version. See the [Git docs](https://git-scm.com/docs/git-tag/2.1.4#_on_re_tagging) for a discussion of this -- they actually have some pretty strong words about it.
