### ISSUE TITLE
最近下载速度很慢且不稳定，是软件的问题吗

### ISSUE THREAD

**Issue by Weilesscodeless** [qjfoidnh/BaiduPCS-Go#122]
最近下载速度很慢且不稳定，是软件的问题吗。之前速度很快的，我用客户端下载正常。

**Comment by qjfoidnh** [comment]
参见#119

**Comment by Weilesscodeless** [comment]
多谢，已经解决了，非常好用。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qjfoidnh/BaiduPCS-Go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qjfoidnh/BaiduPCS-Go] 最近下载速度很慢且不稳定，是软件的问题吗 (#122)





 
参见#119
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
