### ISSUE TITLE
蓝奏云链接失效了

### ISSUE THREAD

**Issue by xiaoming902** [qjfoidnh/BaiduPCS-Go#123]
rt

**Comment by qjfoidnh** [comment]
蓝奏云后续可能就随缘了，版本更新以release为准

**Comment by Rorotaroho** [comment]
> 蓝奏云后续可能就随缘了，版本更新以release为准
> […](#)
> 在 2021年8月28日，下午2:50，xiaoming902 ***@***.***> 写道： ﻿ rt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

直接先打开官网再拼接地址可以访问。虽然我也不知道为什么从这里跳转就不行

**Comment by mayii2001** [comment]
readme里蓝奏链接写错了，少了个w
