### ISSUE TITLE
求救啊，为啥不能复制黏贴进去？

### ISSUE THREAD

**Issue by conmor** [qjfoidnh/BaiduPCS-Go#124]
求救啊，为啥不能复制黏贴进去？

https://files.catbox.moe/7u1n5m.mp4

连着按了很多下都黏贴不进去。。。
这是为啥？

**Comment by conmor** [comment]
难道要手打bduss吗？

**Comment by qjfoidnh** [comment]
呃……就正常往终端里粘贴文字那么搞啊……

**Comment by conmor** [comment]
......特地用手机重录了一次
可就是黏贴不进去啊
https://files.catbox.moe/1k5vy8.mp4

**Comment by qjfoidnh** [comment]
cmd里粘贴是直接右键
