### ISSUE TITLE
生成的直链下载提示 {"error_code":31362,"error_msg":"sign error","error_info":"","request_id":5623105483546638}

### ISSUE THREAD

**Issue by monkey0416** [qjfoidnh/BaiduPCS-Go#125]
已经设置user_agent，下载提示 {"error_code":31362,"error_msg":"sign error","error_info":"","request_id":5623105483546638} 请问是只有我一个人碰到还是？

小于50m的文件没问题，大于50m就不可以

**Comment by qjfoidnh** [comment]
下载用的user-agent必须与生成链接时的ua一致（即pcs-go的panUA），否则即会sign error

**Comment by monkey0416** [comment]
> 下载用的user-agent必须与生成链接时的ua一致（即pcs-go的panUA），否则即会sign error

是的一摸一样的，就是和生成直链的时候 控制台提示输入 user_agent 的值一摸一样

**Comment by qjfoidnh** [comment]
用的下载工具是什么？

另外BaiduPCS-GO的panUA要按 #119 中手动更换，不能用netdisk;2.2.51.6;netdisk;10.0.63;PC;android-android

**Comment by monkey0416** [comment]
> 用的下载工具是什么？ 另外BaiduPCS-GO的panUA要按 #119 中手动更换，不能用netdisk;2.2.51.6;netdisk;10.0.63;PC;android-android
> […](#)
> 在 2021年8月31日，下午6:04，monkey0416 ***@***.***> 写道： ﻿ 下载用的user-agent必须与生成链接时的ua一致（即pcs-go的panUA），否则即会sign error 是的一摸一样的，就是和生成直链的时候 控制台提示输入 user_agent 的值一摸一样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我是Mac系统 用的 Motrix 嗯嗯是的 按照#119 替换了的

**Comment by qjfoidnh** [comment]
Motrix的请求头里没有Range参数，所以不受支持

**Comment by devil233-ui** [comment]
> Motrix的请求头里没有Range参数，所以不受支持

佬能帮忙看看我的么，下面三个直链打开和楼主一样。
我是用的[这个插件](https://gitee.com/TimeRainStarSky/TRSS-Plugin/)，系统是linux。
另外我的下载文件功能是正常使用的。

> > BaiduPCS-Go:devil 海滨热梦$ config set -user_agent="netdisk;P2SP;3.0.0.8;netdisk;11.12.3;ANG-AN00;android-android;10.0;JSbridge4.4.0;jointBridge;1.1.0;"
>   名称                  值                                                                                                   建议值                                                                                                                     描述                                                                                                                                     
>   appid                 266719                                                                                                                                                                                                                          百度 PCS 应用ID                                                                                                                          
>   cache_size            64.00KB                                                                                              1KB ~ 256KB                                                                                                                下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值                                                                                     
>   max_parallel          1                                                                                                    1 ~ 14                                                                                                                     下载总最大并发量                                                                                                                         
>   max_upload_parallel   4                                                                                                    1 ~ 100                                                                                                                    上传单文件最大并发量                                                                                                                     
>   max_download_load     1                                                                                                    1 ~ 5                                                                                                                      同时进行下载文件的最大数量                                                                                                               
>   max_download_rate     不限制                                                                                                                                                                                                                          限制最大下载速度, 0代表不限制                                                                                                            
>   max_upload_rate       不限制                                                                                                                                                                                                                          限制最大上传速度, 0代表不限制                                                                                                            
>   max_upload_load       4                                                                                                    1-4                                                                                                                        同时进行上传文件的最大数量                                                                                                               
>   savedir               /root/TRSS_AllBot/home/Downloads                                                                                                                                                                                                下载文件的储存目录                                                                                                                       
>   enable_https          true                                                                                                 true                                                                                                                       启用 https                                                                                                                               
>   force_login_username                                                                                                       留空                                                                                                                       强制登录指定用户名, 适用于tieba用户信息接口不可用的情况, 如登录正常请留空                                                                
>   no_check              true                                                                                                 true                                                                                                                       关闭下载文件md5校验                                                                                                                      
>   ignore_illegal        false                                                                                                false                                                                                                                      关闭上传文件的文件名非法字符检查                                                                                                         
>   upload_policy         fail                                                                                                 fail                                                                                                                       上传遇到重名文件时的处理策略, fail(默认，直接返回失败)、newcopy(重命名文件)、overwrite(覆盖)、skip(跳过)、rsync(仅跳过大小未变化的文件)  
>   user_agent            netdisk;P2SP;3.0.0.8;netdisk;11.12.3;ANG-AN00;android-android;10.0;JSbridge4.4.0;jointBridge;1.1.0;  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36  浏览器标识                                                                                                                               
>   pcs_ua                                                                                                                                                                                                                                                PCS 浏览器标识                                                                                                                           
>   pcs_addr              pcs.baidu.com                                                                                        pcs.baidu.com                                                                                                              PCS 服务器地址                                                                                                                           
>   pan_ua                netdisk;P2SP;3.0.0.8;netdisk;11.12.3;ANG-AN00;android-android;10.0;JSbridge4.4.0;jointBridge;1.1.0;  netdisk;P2SP;3.0.0.8;netdisk;11.12.3;ANG-AN00;android-android;10.0;JSbridge4.4.0;jointBridge;1.1.0;                        Pan 浏览器标识                                                                                                                           
>   proxy                                                                                                                                                                                                                                                 设置代理, 支持 http/socks5 代理                                                                                                          
>   local_addrs                                                                                                                                                                                                                                           设置本地网卡地址, 多个地址用逗号隔开                                                                                                     
> 
> 保存配置成功!
> 
> BaiduPCS-Go:devil 海滨热梦$ lt /devil/xx
> [0] /devil/xx
>   #                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  链接                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
>   0  https://bjbgp01.baidupcs.com/file/870248f92i077fce70f5dcc249a28f04?bkt=en-d3a65691252603d35425c2b76a1cf6bb4ce72934b1c46acfc22fe98a621007786e9a588cdab4f4e4&fid=2043151874-250528-548178826468170&time=1727768902&sign=FDTAXUbGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-J0dryScFyxjHVQkQuxSkJGdGgSc%3D&to=75&size=1721735254&sta_dx=1721735254&sta_cs=1079&sta_ft=rar&sta_ct=7&sta_mt=6&fm2=MH%2CYangquan%2CAnywhere%2C%2CNone%2Cany&ctime=1633874349&mtime=1708967981&dt3=7&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1721735254&vuk=2043151874&iv=2&vl=8&htype=&randtype=&tkbind_id=0&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-9036cf8e3cca0832d935f13cd3afd659189354ceeb0bdbd87a134b1ce53931dfc624b083cb02de7b&expires=8h&rt=pr&r=534626971&vbdid=2872214264&fin=%E3%80%90Pc%E5%A4%A9%E9%82%88%2B%E9%BB%84%E6%B3%89%E3%80%91Raging.Loop%E3%80%90%E5%AF%86%E7%A0%81%E7%BB%88%E7%82%B9%E3%80%91.rar&bflag=75,80,14,19-75&check_blue=1&rtype=1&devuid=25CB648B50BCA393E343C276D4C01453%7C0&clienttype=17&channel=0&cuid=25CB648B50BCA393E343C276D4C01453%7C0&dp-logid=8675951253101907344&dp-callid=0.1&hps=1&tsl=0&csl=0&fsl=-1&csign=E1%2FhdeZNSPJOlJMyp7Zp2Qr%2Fd9E%3D&so=0&ut=1&uter=3&serv=0&uc=2315619645&ti=05df9239daa40647720672ef301bb4f230fe5f8af0a9e26a&hflag=30&from_type=3&adg=c_25cb648b50bca393e343c276d4c01453&reqlabel=250528_l_0d379c25691f1db02fd2dff786ffd19a_-1_b47a1c84a207d217ae9410ea0984f09f&ibp=1&fpath=devil%2F%E4%BA%BA%E7%8B%BC%E6%9D%91%E4%B9%8B%E8%B0%9C&mt_scene=personal&by=themis     
>   1  https://allall02.baidupcs.com/file/870248f92i077fce70f5dcc249a28f04?bkt=en-d3a65691252603d35425c2b76a1cf6bb4ce72934b1c46acfc22fe98a621007786e9a588cdab4f4e4&fid=2043151874-250528-548178826468170&time=1727768902&sign=FDTAXUbGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-YLRjW01Vcgemox79O617YZPcyiQ%3D&to=80&size=1721735254&sta_dx=1721735254&sta_cs=1079&sta_ft=rar&sta_ct=7&sta_mt=6&fm2=MH%2CYangquan%2CAnywhere%2C%2CNone%2Cany&ctime=1633874349&mtime=1708967981&dt3=7&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1721735254&vuk=2043151874&iv=2&vl=8&htype=&randtype=&tkbind_id=0&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-9036cf8e3cca0832d935f13cd3afd659189354ceeb0bdbd87a134b1ce53931dfc624b083cb02de7b&expires=8h&rt=pr&r=902486684&vbdid=2872214264&fin=%E3%80%90Pc%E5%A4%A9%E9%82%88%2B%E9%BB%84%E6%B3%89%E3%80%91Raging.Loop%E3%80%90%E5%AF%86%E7%A0%81%E7%BB%88%E7%82%B9%E3%80%91.rar&bflag=75,80,14,19-80&check_blue=1&rtype=1&devuid=25CB648B50BCA393E343C276D4C01453%7C0&clienttype=17&channel=0&cuid=25CB648B50BCA393E343C276D4C01453%7C0&dp-logid=8675951253101907344&dp-callid=0.1&hps=1&tsl=0&csl=0&fsl=-1&csign=E1%2FhdeZNSPJOlJMyp7Zp2Qr%2Fd9E%3D&so=0&ut=1&uter=3&serv=0&uc=2315619645&ti=05df9239daa40647720672ef301bb4f230fe5f8af0a9e26a&hflag=30&from_type=3&adg=c_25cb648b50bca393e343c276d4c01453&reqlabel=250528_l_0d379c25691f1db02fd2dff786ffd19a_-1_b47a1c84a207d217ae9410ea0984f09f&ibp=1&fpath=devil%2F%E4%BA%BA%E7%8B%BC%E6%9D%91%E4%B9%8B%E8%B0%9C&mt_scene=personal&by=themis    
>   2  https://bjbgp01.baidupcs.com/file/870248f92i077fce70f5dcc249a28f04?bkt=en-d3a65691252603d35425c2b76a1cf6bb4ce72934b1c46acfc22fe98a621007786e9a588cdab4f4e4&fid=2043151874-250528-548178826468170&time=1727768902&sign=FDTAXUbGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-gs35KAYz9A2eFZxSwt8cfvjgouI%3D&to=14&size=1721735254&sta_dx=1721735254&sta_cs=1079&sta_ft=rar&sta_ct=7&sta_mt=6&fm2=MH%2CYangquan%2CAnywhere%2C%2CNone%2Cany&ctime=1633874349&mtime=1708967981&dt3=7&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1721735254&vuk=2043151874&iv=2&vl=8&htype=&randtype=&tkbind_id=0&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-9036cf8e3cca0832d935f13cd3afd659189354ceeb0bdbd87a134b1ce53931dfc624b083cb02de7b&expires=8h&rt=pr&r=666320121&vbdid=2872214264&fin=%E3%80%90Pc%E5%A4%A9%E9%82%88%2B%E9%BB%84%E6%B3%89%E3%80%91Raging.Loop%E3%80%90%E5%AF%86%E7%A0%81%E7%BB%88%E7%82%B9%E3%80%91.rar&bflag=75,80,14,19-14&check_blue=1&rtype=1&devuid=25CB648B50BCA393E343C276D4C01453%7C0&clienttype=17&channel=0&cuid=25CB648B50BCA393E343C276D4C01453%7C0&dp-logid=8675951253101907344&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=E1%2FhdeZNSPJOlJMyp7Zp2Qr%2Fd9E%3D&so=1&ut=1&uter=3&serv=0&uc=2315619645&ti=05df9239daa40647720672ef301bb4f230fe5f8af0a9e26a&hflag=30&from_type=3&adg=c_25cb648b50bca393e343c276d4c01453&reqlabel=250528_l_0d379c25691f1db02fd2dff786ffd19a_-1_b47a1c84a207d217ae9410ea0984f09f&ibp=1&fpath=devil%2F%E4%BA%BA%E7%8B%BC%E6%9D%91%E4%B9%8B%E8%B0%9C&mt_scene=personal&by=themis           
>   3  https://allall02.baidupcs.com/file/870248f92i077fce70f5dcc249a28f04?bkt=en-d3a65691252603d35425c2b76a1cf6bb4ce72934b1c46acfc22fe98a621007786e9a588cdab4f4e4&fid=2043151874-250528-548178826468170&time=1727768902&sign=FDTAXUbGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-IR5tp4L%2FMcZF%2Fz4%2FFchRGM%2Bf2RA%3D&to=19&size=1721735254&sta_dx=1721735254&sta_cs=1079&sta_ft=rar&sta_ct=7&sta_mt=6&fm2=MH%2CYangquan%2CAnywhere%2C%2CNone%2Cany&ctime=1633874349&mtime=1708967981&dt3=7&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1721735254&vuk=2043151874&iv=2&vl=8&htype=&randtype=&tkbind_id=0&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-9036cf8e3cca0832d935f13cd3afd659189354ceeb0bdbd87a134b1ce53931dfc624b083cb02de7b&expires=8h&rt=pr&r=205801012&vbdid=2872214264&fin=%E3%80%90Pc%E5%A4%A9%E9%82%88%2B%E9%BB%84%E6%B3%89%E3%80%91Raging.Loop%E3%80%90%E5%AF%86%E7%A0%81%E7%BB%88%E7%82%B9%E3%80%91.rar&bflag=75,80,14,19-19&check_blue=1&rtype=1&devuid=25CB648B50BCA393E343C276D4C01453%7C0&clienttype=17&channel=0&cuid=25CB648B50BCA393E343C276D4C01453%7C0&dp-logid=8675951253101907344&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=E1%2FhdeZNSPJOlJMyp7Zp2Qr%2Fd9E%3D&so=1&ut=1&uter=3&serv=0&uc=2315619645&ti=05df9239daa40647720672ef301bb4f230fe5f8af0a9e26a&hflag=30&from_type=3&adg=c_25cb648b50bca393e343c276d4c01453&reqlabel=250528_l_0d379c25691f1db02fd2dff786ffd19a_-1_b47a1c84a207d217ae9410ea0984f09f&ibp=1&fpath=devil%2F%E4%BA%BA%E7%8B%BC%E6%9D%91%E4%B9%8B%E8%B0%9C&mt_scene=personal&by=themis  
> 
> 提示: 访问下载链接, 需将下载器的 User-Agent 设置为: netdisk;P2SP;3.0.0.8;netdisk;11.12.3;ANG-AN00;android-android;10.0;JSbridge4.4.0;jointBridge;1.1.0;
