### ISSUE TITLE
下载中会终止进程

### ISSUE THREAD

**Issue by ChanucyHe** [qjfoidnh/BaiduPCS-Go#127]
[3] ↓ 352.00MB/5.89GB 81.34MB/s in 11.27s, left 1m9s ............Killed
不知知道为什么，会终止，在下载命令后面加 2>&1有时候不会，下载参数都是默认的，并发那些都没设置，本身也是svip,尝试-p 5也是同样情况

**Comment by qjfoidnh** [comment]
单线程下载SVIP应该也到不了这个速度的，建议确认一下并发数

这个问题过去没人报过，但可以把下载缓冲调大点试试

config set -cache_size=100M

**Comment by VashStan** [comment]
> [3] ↓ 352.00MB/5.89GB 81.34MB/s in 11.27s, left 1m9s ............Killed 不知知道为什么，会终止，在下载命令后面加 2>&1有时候不会，下载参数都是默认的，并发那些都没设置，本身也是svip,尝试-p 5也是同样情况

我下载了一个30W个文件 的数据集，总是kill，经过验证，最后减少并发 + 设置缓存为2GB 解决了。仅供参考
