### ISSUE TITLE
ls显示不了目录信息，转存失败

### ISSUE THREAD

**Issue by Weilesscodeless** [qjfoidnh/BaiduPCS-Go#128]
显示获取文件/目录的元信息, 遇到错误, 未知返回数据。不清楚是不是账号问题，请问有办法解决吗？

**Comment by qjfoidnh** [comment]
ls命令本地未发现异常，建议检查网络配置

**Comment by Ayke** [comment]
相同问题，ls返回如下信息：

获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized

已经logout之后重新login，网络也没问题

**Comment by Ayke** [comment]
已解决：

> 如果遇到31301，无法切换目录的问题，AppID没有根目录权限，换回266719就可以了,在当前目录输入config set -appid=266719
> 这个 AppID 只有读取 /apps/baidu_shurufa 的权限 访问其他目录要换回 310646,config set -appid=310646
