### ISSUE TITLE
请问能否支持代理

### ISSUE THREAD

**Issue by kdurov** [qjfoidnh/BaiduPCS-Go#129]
你好，

最近发现本地ISP可能分配到被墙的IP，于是便无法上传到度盘。
请问能否添加代理参数的支持以便绕过GFW。

谢谢。

(update: 我是用win下的bin上传的，linux可以配置环境，win下不知道如何配置。)

**Comment by qjfoidnh** [comment]
win下cmd里全局代理设置为set https_proxy=xxxx:xxxx
或者在PCS-Go里也支持设置，config set -proxy=xxxx:xxxx

**Comment by kdurov** [comment]
谢谢。看了下help没提到代理以为不能用。

**Comment by 10362227** [comment]
这种代理设置没用，传输的时候没有走代理，我实测了

**Comment by qjfoidnh** [comment]
> 这种代理设置没用，传输的时候没有走代理，我实测了

代理设置无问题，建议检查配置

**Comment by 10362227** [comment]
> > 这种代理设置没用，传输的时候没有走代理，我实测了
> 
> 代理设置无问题，建议检查配置

我搞错了

**Comment by kdurov** [comment]
> > 这种代理设置没用，传输的时候没有走代理，我实测了
> 
> 代理设置无问题，建议检查配置

建议添加参数实现指定传输走代理。每次都要修改config文件太费时了。
