### ISSUE TITLE
路径含有 【'】无法上传

### ISSUE THREAD

**Issue by haobinnan** [qjfoidnh/BaiduPCS-Go#131]
我今天上传一个目录，最终比较发现上传数量不对，发现 含有 ' 路径的文件无法上传，请修正
S251 Daddy Pig's Birthday.mp4

**Comment by haobinnan** [comment]
可能没有进行转义

**Comment by qjfoidnh** [comment]
单引号文件名可能在某些情况下引发问题，目前当做非法文件名过滤，并非转义问题

**Comment by haobinnan** [comment]
但是这样 有些文件容易溜掉，不完美啊。

**Comment by haobinnan** [comment]
我看了一下 百度的确不允许单引号，如果这样最好用其它字符替换一下例如用下划线_

**Comment by haobinnan** [comment]
文件名不能包含以下字符：<,>,|,*,?,,/

**Comment by haobinnan** [comment]
他给的提示 也没有单引号啊

**Comment by haobinnan** [comment]
通过浏览器不能含有 单引号 但是用 百度网盘的app可以有单引号

**Comment by qjfoidnh** [comment]
百度网盘对单引号支持不完美，请在本地手动修改掉非法字符再上传

**Comment by haobinnan** [comment]
有很多这样的文件，最好咱们程序能支持一下 通过web端不行，但是通过百度网盘的windows端可以新建带有单引号的文件名“S251 Daddy Pig's Birthday.mp4”

**Comment by haobinnan** [comment]
这个问题 如果不解决，会给使用者造成损失，例如 以为都上传到网盘中了，实际有些文件并未上传，然后本地源文件还删除了。

**Comment by qjfoidnh** [comment]
因非法字符上传失败是有跳过提示的。
未来版本不会支持单引号，个别需要可fork修改判断函数自行编译
BaiduPCS-Go/pcsutil/file.go 114行 func ChPathLegal

**Comment by haobinnan** [comment]
为什么不支持一下？如果上传一个大目录 即便有跳过信息用户可能也看不到，因为顶没了。

**Comment by 362227** [comment]
说真的，不支持单引号、逗号这些字符，并不明智。这种英文文件名太常见了，你可以用youtube-dl下载视频，很多标题都有引号、逗号

**Comment by haobinnan** [comment]
如果存了很多国外文献，有一些标题就有单引号。感觉还是应该支持一下。

**Comment by 362227** [comment]
> 我看了一下 百度的确不允许单引号，如果这样最好用其它字符替换一下例如用下划线_

为什么我测试正常，用电脑客户端测试的，而且用了这么久没发现什么问题，好像就没有提醒过文件名问题

**Comment by haobinnan** [comment]
电脑端可以有单引号 web不行

**Comment by haobinnan** [comment]
还是推荐处理一下这个问题。

**Comment by haobinnan** [comment]
感谢新版本的改进。
