### ISSUE TITLE
ArchLinux下无法登录帐号，输入2次验证码后弹错。

### ISSUE THREAD

**Issue by ZSPAPAPA** [qjfoidnh/BaiduPCS-Go#133]
panic: runtime error: slice bounds out of range [:11] with capacity 1

goroutine 1 [running]:
bytes.Replace({0xc000360c00, 0xc000360c00, 0x30}, {0xc00051b43f, 0xc00051b430, 0x1}, {0x0, 0x0, 0xc00051b4a8}, 0xffffffffffffffff)
        bytes/bytes.go:1017 +0x53c
github.com/qjfoidnh/baidu-tools/tieba/tiebautil.TiebaClientRawQuerySignature({0xc000360c00, 0x30})
        github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tiebautil/client_signature.go:59 +0xc7
github.com/qjfoidnh/baidu-tools/tieba.NewUserInfoByUID(0x2e2ad21e)
        github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tieba_info.go:19 +0xd3
github.com/qjfoidnh/baidu-tools/tieba.(*Tieba).FlushUserInfo(0xc0002e5040)
        github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tieba_info.go:86 +0x8c
github.com/qjfoidnh/baidu-tools/tieba.NewUserInfoByBDUSS({0xc0005ceb46, 0xc000690540})
        github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tieba_login.go:68 +0xd54
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig.NewUserInfoByBDUSS({0xc0005ceb46, 0xc0003b82b0})
        github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig/baidu.go:88 +0x27
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig.(*PCSConfig).SetupUserByBDUSS(0xc000152a20, {0xc0005ceb46, 0x0}, {0xc0004c87e7, 0x20}, {0xc0002c70a7, 0x40}, {0xc0002af000, 0xc000152a20})
        github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig/maniper.go:124 +0xcf
main.main.func5(0xc00013f340)
        github.com/qjfoidnh/BaiduPCS-Go/main.go:441 +0x277
github.com/urfave/cli.HandleAction({0x557bf4c4eb40, 0x557bf4d01b20}, 0x5)
        github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x557bf48835e1, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x557bf488db61, 0x12}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc00017c8c0, {0xc000020040, 0x2, 0x2})
        github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
        github.com/qjfoidnh/BaiduPCS-Go/main.go:2204 +0x6545

**Comment by qjfoidnh** [comment]
#126 
下个版本将修复

**Comment by ufbycd** [comment]
修复了吗？我的在Manjaro Linux系统上也是如此。

**Comment by ufbycd** [comment]
哦，重新抓git编译就没问题了。
