### ISSUE TITLE
能否禁止上传正在使用的文件

### ISSUE THREAD

**Issue by 10362227** [qjfoidnh/BaiduPCS-Go#137]
我用的是脚本定时上传文件，但有时候有的文件正在下载，都不完整，它也会上传。rclone、度盘客户端都会提示无法上传正在使用的文件

**Comment by qjfoidnh** [comment]
应该要涉及调用操作系统的接口，Go语言怎么实现我还不太了解

**Comment by 10362227** [comment]
> 应该要涉及调用操作系统的接口，Go语言怎么实现我还不太了解

rclone的原理是检测文件大小短时间内是否在变化，就算是下载设置了预分配大小，我看了下文件大小也在变化，不过极其微小
