### ISSUE TITLE
分享链接转存到网盘失败: 当前目录下已有IQAbigdatabase_v2_20200922_public同名文件/文件夹

### ISSUE THREAD

**Issue by Usernamezhx** [qjfoidnh/BaiduPCS-Go#14]
https://pan.baidu.com/s/112NJIx2kNQvfmSbrUUBtFw
password: r32i
这个显示的是当前目录下已有IQAbigdatabase_v2_20200922_public同名文件/文件夹， 但是当前目录下并没有这个文件

你好这个转存没有数量限制吗？这个分享里有20w的文件

**Comment by qjfoidnh** [comment]
你好，看了一下，转存是有上限的，跟官方一致；这里是误报，没有识别转存超出上限的错误代码，下一个版本将完善。

以后有精力可能会尝试解决转存数量限制

**Comment by Usernamezhx** [comment]
感谢你的回复
