### ISSUE TITLE
在linux客户端上download命令可以正常下载，但用loacate命令导出的下载链接无法正常下载，IDM的UA已经修改为要求的user_agent

### ISSUE THREAD

**Issue by OnePerson2020** [qjfoidnh/BaiduPCS-Go#142]
在linux客户端上download命令可以正常下载，但用loacate命令导出的下载链接无法正常下载，IDM的UA已经修改为要求的user_agent

**Comment by qjfoidnh** [comment]
下载请求头中必须带有Range:xxx-xxx，IDM应该是缺这个
