### ISSUE TITLE
下载的文件夹中文件过多会报错

### ISSUE THREAD

**Issue by crazyn2** [qjfoidnh/BaiduPCS-Go#143]
树莓派4B
操作系统: Ubuntu-server-20.04
程序文件:BaiduPCS-Go-v3.8.4-linux-arm64.zip

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a1514]

goroutine 519 [running]:
net.(*Resolver).tryOneName(0xa1d540, 0x6b54d8, 0x4000901240, 0x400026a3c0, 0x4000ac8c70, 0x10, 0x4000b1001c, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:253 +0x1e4
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xa1d540, 0x6b54d8, 0x4000901240, 0x400026a3c0, 0x4000ac8c70, 0x10, 0x4000aad080, 0x59001c)
	/usr/local/go/src/net/dnsclient_unix.go:601 +0x7c
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
	/usr/local/go/src/net/dnsclient_unix.go:600 +0xb4

**Comment by qjfoidnh** [comment]
老问题了，原因至今没能定位，只是怀疑跟go域名解析的实现有关系

**Comment by crazyn2** [comment]
多谢解答，那issue先closed了
