### ISSUE TITLE
请给download命令增加两个参数--on-download-complete和--on-all-download-complete

### ISSUE THREAD

**Issue by karma-sun** [qjfoidnh/BaiduPCS-Go#145]
请给download命令增加两个参数--on-download-complete和--on-all-download-complete，指定外部程序在下载完自动执行

**Comment by qjfoidnh** [comment]
额。。。啥意思？是说回调么

**Comment by konghui** [comment]
他可能是想在任务完成之后想调一些自己的命令，比如关机之类的吧，我理解应该是这样

**Comment by karma-sun** [comment]
是的，楼上说的对

**Comment by cnlinjie** [comment]
虽然加了个「请」字，但感觉还是有点命令的语气。
建议使用：如果可以的话，能不能.... ，谢谢。
比如：
如果可以的话，能不能给 download命令增加两个参数--on-download-complete和--on-all-download-complete ，谢谢。

如果还加上动机或者原因，就更好了。

**Comment by qjfoidnh** [comment]
回调逻辑并不适合做到程序里，建议在shell脚本里，通过检测BaiduPCS-GO的输出来实现类似效果
