### ISSUE TITLE
邮箱登陆，发送邮件验证码 有问题了，如果是手机验证码应该也一样。

### ISSUE THREAD

**Issue by 24** [qjfoidnh/BaiduPCS-Go#15]
### 调用到 baidu-login 的地方，

```
func (lj *LoginJSON) parsePhoneAndEmail(bc *BaiduClient) {
```
从 GotoURL 里面已经获取不到Token了。但是有个ltoken。 

如果把这个ltoken 当作token 传递下去，能得到已发送验证码，但是收不到验证码。

我不太这个登陆流程。

@qjfoidnh  看看呢？ :)

**Comment by qjfoidnh** [comment]
Login接口变化比较大，而且不唯一了。
目前已经可以接收手机/邮箱验证码，可能需要更多测试；另一个问题就是验证完成后还需要进行两次图片验证码，否则无法获取到正确的stoken

**Comment by 24** [comment]
如果后面还改，那还不如废弃掉算了。用cookie 登陆更省事
