### ISSUE TITLE
如何确保上传文件的完整性。

### ISSUE THREAD

**Issue by Hyvi** [qjfoidnh/BaiduPCS-Go#150]
看了 Readme， 分块上传时 MD5 可能存在不正确的情况。 
用 BaiduPCS-Go 如何保证上传文件的完整性的呢？

**Comment by qjfoidnh** [comment]
不正确是指分块组合成的完整文件的md5。只要各个分块传输正确，组合成的文件就可以认为是正确的；至于分块传输正确应该是由tcp的可靠性来保证
