### ISSUE TITLE
下载速度很慢，换pan_ua也不行

### ISSUE THREAD

**Issue by LoveChina-3000** [qjfoidnh/BaiduPCS-Go#151]
![image](https://user-images.githubusercontent.com/8185255/141883573-3ce817f1-f247-4b30-a250-909f905760b0.png)

**Comment by qjfoidnh** [comment]
可确认
1. 账号是无异常的svip
2. 已更新至最新版本，且更换的panua是推荐的合法ua

发自我的iPhone

**Comment by fanzhen1** [comment]
我也是同样问题：svip，官方客户端下载速度正常，程序是最新的3.8.4，pan_ua用了https://github.com/qjfoidnh/BaiduPCS-Go/issues/119 您推荐的最后一个，但下载速度始终是0，偶尔跳出个十几kb

![image](https://user-images.githubusercontent.com/20765667/142172024-1d7fe2ee-e795-4f3d-bf8a-9fe50799a443.png)

**Comment by qjfoidnh** [comment]
这个不太好排查，可以再换下UA试试......
