### ISSUE TITLE
下载文件失败，提示 `panic: runtime error`

### ISSUE THREAD

**Issue by taicaile** [qjfoidnh/BaiduPCS-Go#152]
你好，

在尝试下载目录的时候，提示如下错误，

![image](https://user-images.githubusercontent.com/23215696/142188534-d26764ea-b5e1-439c-9155-0157fa67e3f8.png)

仅下载这个资源有问题，不知道是什么原因。

**Comment by qjfoidnh** [comment]
能分享下吗？我试试能否复现

**Comment by taicaile** [comment]
> 能分享下吗？我试试能否复现

可以的，

链接: https://pan.baidu.com/s/1c18ibw1GG2kUsYAnQt214g 提取码: ef51

**Comment by qjfoidnh** [comment]
本地未能复现。
根据过往一些使用者的经验，将dns设置为阿里云或114等公共DNS，然后清除dns缓存可能会有用

**Comment by taicaile** [comment]
> 本地未能复现。
> 
> 根据过往一些使用者的经验，将dns设置为阿里云或114等公共DNS，然后清除dns缓存可能会有用

好的，我都试一下。
