### ISSUE TITLE
请问这是什么错误

### ISSUE THREAD

**Issue by kpking** [qjfoidnh/BaiduPCS-Go#153]
保存配置错误: truncate /root/.config/BaiduPCS-Go/pcs_config.json: no space left on device

**Comment by qjfoidnh** [comment]
磁盘空间是不是满了

发自我的iPhone

**Comment by kpking** [comment]
是的~有没有办法把/pcs_config.json移动到其他地方？

**Comment by qjfoidnh** [comment]
可通过设置环境变量 BAIDUPCS_GO_CONFIG_DIR, 指定配置文件存放的目录.

但root目录都没空间了有点危险啊……

发自我的iPhone
