### ISSUE TITLE
`BaiduPCS-Go transfer <地址> <提取码>`转存失败

### ISSUE THREAD

**Issue by smilingpoplar** [qjfoidnh/BaiduPCS-Go#157]
分享链接转存到网盘失败: 未知错误, 错误代码2

BaiduPCS-Go version v3.8.4

在transfer.go的`GenerateRequestQuery`中打印log，
```
{"errno":2,"newno":"","request_id":3470148233719957538,"show_msg":"参数错误"}
```

**Comment by qjfoidnh** [comment]
这里得看下具体的地址和提取码

**Comment by smilingpoplar** [comment]
@qjfoidnh  比如`BaiduPCS-Go transfer pan.baidu.com/s/1KlfHSxsSp1MDwmUODiKYyQ 72ZN`

**Comment by qjfoidnh** [comment]
上述地址在本地测试正常转存

**Comment by smilingpoplar** [comment]
@qjfoidnh 是3.8.4版本吗？我怎么mac版和linux版试了都不行
3.8.3, 3.8.2也不行...

**Comment by qjfoidnh** [comment]
是的......
