### ISSUE TITLE
请问能不能生成单个秒传而不是导出txt

### ISSUE THREAD

**Issue by tallape** [qjfoidnh/BaiduPCS-Go#16]
因为我需求是获得网盘内单个文件的秒传链接。但是目前好像只有导出到txt的命令。

**Comment by qjfoidnh** [comment]
下个版本将增加直接输出到控制台的选项

**Comment by potus2030** [comment]
导出到txt好啊，怎么操作的？ 用>输出定向？

**Comment by qjfoidnh** [comment]
> 导出到txt好啊，怎么操作的？ 用>输出定向？
https://github.com/felixonmars/BaiduPCS-Go/issues/33#issuecomment-756195641
