### ISSUE TITLE
多线程下载并没有起到作用

### ISSUE THREAD

**Issue by zh5j** [qjfoidnh/BaiduPCS-Go#161]
RT，SVIP帐号通过BDUSS+STOKEN登陆，下载某大文件设置-p 16 -l 16，然而后台网络检测发现只有一个TCP连接。貌似多线程下载并没有起作用。

**Comment by qjfoidnh** [comment]
嗯。。。用的版本号是多少呢
另外看tcp连接数的命令也可以发下

**Comment by zh5j** [comment]
刚刚更新的。3.8.5版本。
命令：ss -tnpa|grep :433
ubuntu21.04系统
（更正，写错了，我筛选的端口是443）

**Comment by qjfoidnh** [comment]
ubuntu18.04系统3.8.5，查到连接数是根据-p指定在变化的，一般是-p数+2
ss -tnpa|grep :443|grep BaiduPCS|wc -l
