### ISSUE TITLE
能否自定义下载文件夹名 或 关闭自动创建以{数字_百度用户名}格式命名的下载文件夹

### ISSUE THREAD

**Issue by voidoath** [qjfoidnh/BaiduPCS-Go#169]
![](https://cdn.jsdelivr.net/gh/voidoath/photo/blog-img/20220129084827.png)
如上图，在config中，已经将savedir设置为/root/Download/baidu，但是程序仍会在该目录下自动创建一个以{数字_百度用户名}格式命名的文件夹，把文件下载到自动创建的文件夹中，对文件相关操作造成不便。能否自定义自动创建的下载文件夹名 或 关闭自动创建以{数字_百度用户名}格式命名的下载文件夹？

**Comment by qjfoidnh** [comment]
在下载时用--saveto指定目录即可
savedir的逻辑继承自原始版本，不少用户也有继续使用的需求
