### ISSUE TITLE
为何下载速度老是0啊，是不是要设置其他的

### ISSUE THREAD

**Issue by focus2846** [qjfoidnh/BaiduPCS-Go#177]
![QQ图片20220222132149](https://user-images.githubusercontent.com/6268423/155068308-92f2ca80-d937-4c33-a7a8-620ac5faf20b.png)

**Comment by qjfoidnh** [comment]
如果之前使用过3.8.4之下的老版本，需要手动修改pan_ua，详见 #119

**Comment by focus2846** [comment]
谢谢
