### ISSUE TITLE
判断转存超过限制的那个地方，有点复杂

### ISSUE THREAD

**Issue by 24** [qjfoidnh/BaiduPCS-Go#18]
用一个普通的账户，去保存的，返回的Json

```
{
    "errno": 12,
    "info": [
        {
            "errno": 120,
            "path": "/test"
        }
    ],
    "limit": 200000,
    "newno": "",
    "non_vip_limit": 500,
    "request_id": 699837755176920600,
    "show_msg": "",
    "target_file_nums": 569,
    "target_file_nums_limit": 500,
    "task_id": 0
}
```

并没有[ _errno = -33](https://github.com/qjfoidnh/BaiduPCS-Go/blob/d846205263471cc496f9e3ad026f7e49bfe5afab/baidupcs/transfer.go#L176)

感觉这个地方，应该还有其他情况的errno

倒是可以直接判断  ```target_file_nums >  target_file_nums_limit``` 来判断是否超过了限制。。

但不一定对。 

 @qjfoidnh  看看。

**Comment by qjfoidnh** [comment]
改成用大于判断了，我这儿普通用户也是-33，可能跟转存的文件也有关系
