### ISSUE TITLE
下载文件名带空格的文件会失败

### ISSUE THREAD

**Issue by tasm07** [qjfoidnh/BaiduPCS-Go#180]
如题
![image](https://user-images.githubusercontent.com/24777391/155927168-9177ab7a-eca5-43e8-8c70-bd010c9fb69b.png)

**Comment by qjfoidnh** [comment]
用引号引起文件名或者反斜杠转义空格

**Comment by tasm07** [comment]
请问有可能让程序直接兼容而无需用户额外操作吗？

**Comment by qjfoidnh** [comment]
命令行下程序都是这样。举个简单的例子，如果空格不做特殊处理，程序如何知道空格后的字符是第一个文件名的一部分还是第二个文件名？
不仅是空格，还存在一些特殊字符，也是类似的逻辑，感兴趣可以稍微学习下linux操作基础

**Comment by tasm07** [comment]
原来是这样，多谢指点
