### ISSUE TITLE
希望在download中添加通过ipv6下载选项

### ISSUE THREAD

**Issue by Omae-Kumiko** [qjfoidnh/BaiduPCS-Go#183]
度盘的cdn已经有v6了，但是目前pcs一般解析到的是v4。

**Comment by Nuevo009** [comment]
因为大部分校园网用户的 ipv4 下载都有一定的限制（限速/限量/收费）等等，所以这个 ipv6 需求还是挺多的。。。

**Comment by qjfoidnh** [comment]
走v4还是v6由操作系统的IP栈，dns配置决定，程序本身未进行限制
