### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by boyodyang** [qjfoidnh/BaiduPCS-Go#185]
COPYRIGHT:
  (c) 2016-2020 iikira.
BaiduPCS-Go:Music boyod$ update
检测更新中, 稍候...
检测到新版本: v3.8.7
是否进行更新 (y/n): y
准备下载更新: BaiduPCS-Go-v3.8.7-linux-arm64.zip
下载发生错误: 503 Service Temporarily Unavailable
BaiduPCS-Go:Music boyod$ update
检测更新中, 稍候...
检测到新版本: v3.8.7
是否进行更新 (y/n): y
准备下载更新: BaiduPCS-Go-v3.8.7-linux-arm64.zip
下载发生错误: 503 Service Temporarily Unavailable
BaiduPCS-Go:Music boyod$ quit

**Comment by qjfoidnh** [comment]
更新源的github镜像失效了，下个版本修复
