### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by boyodyang** [qjfoidnh/BaiduPCS-Go#186]
下载最大并发量和最大同时下载数
这两个有什么区别？
我svip
设定为10和5，没问题吧？

**Comment by qjfoidnh** [comment]
若同时下载5文件，则每个文件分到2线程。所以只要下载最大并发量控制住就OK
设为10可以

**Comment by boyodyang** [comment]
感谢

**Comment by boyodyang** [comment]
再问一下，我抓到的包前面没有netdisk;P2SP;3.0.0.8;这一段。这一段需不需要加上去？我看你给的都有，默认配置也有。
