### ISSUE TITLE
获取目录下的文件列表: 网络错误

### ISSUE THREAD

**Issue by SeasonG-CN** [qjfoidnh/BaiduPCS-Go#189]
**ls
获取目录下的文件列表: 网络错误, Get "http://pcs.baidu.com/rest/2.0/pcs/file?app_id=266719&by=name&limit=0-2147483647&method=list&order=asc&path=%2FTemp": dial tcp [240e:944:3001:6:0:ff:b09a:14c]:80: connectex: A connection attempt failed because the connected party did n
ot properly respond after a period of time, or established connection failed because connected host has failed to respond.**

**Comment by qjfoidnh** [comment]
应该是偶发网络问题，一直出现可以把https打开试试
