### ISSUE TITLE
请问可以自定义提取码吗

### ISSUE THREAD

**Issue by qazwsdc** [qjfoidnh/BaiduPCS-Go#20]
比如share s -p 1234 test.zip

**Comment by qjfoidnh** [comment]
不太复杂，下个版本会加上

**Comment by tallape** [comment]
如果加上自定义提取码，那顺便也加上自定义分享时间吧。 ：）

**Comment by wrwe3888** [comment]
@qjfoidnh 自定义提取码和分享时间，什么时候能有呢？谢谢。

**Comment by qjfoidnh** [comment]
最新版本已经出了噢

**Comment by Li5264a** [comment]
> 最新版本已经出了噢

请问现在还支持吗？没看到相关的命令呢
