### ISSUE TITLE
是否存在任何交流群呢？

### ISSUE THREAD

**Issue by MFYDev** [qjfoidnh/BaiduPCS-Go#23]
首先非常感谢qjfoidnh能够继续开发这个工具，我之前作为一个此工具重度使用者找了好久才找到这个，不知道是否存在任何交流群呢？如果没有的话，不如建个交流群？

**Comment by qjfoidnh** [comment]
个人不建议建群哈，招来风指不定哪天这个库也没了

欢迎提issue和pull requests

**Comment by MFYDev** [comment]
好的好的，辛苦了，再次感谢
