### ISSUE TITLE
分享链接转存到网盘失败: 分享码错误

### ISSUE THREAD

**Issue by cloudinstone** [qjfoidnh/BaiduPCS-Go#234]
在差不多转存了1万多个文件1TB以后，transfer后提示"分享链接转存到网盘失败: 分享码错误"。
分享码是正确的。
换帐号也一样。
但也不可能是封IP，手动浏览器转存仍然是正常的。
有哪些知道可能的原因？
多谢。

**Comment by qjfoidnh** [comment]
v3.8.8对转存接口做了一些调整，但仍有概率失败，暂无完美解决方案

**Comment by qjfoidnh** [comment]
v3.9.0已彻底修复
