### ISSUE TITLE
转存失败,未知错误-62

### ISSUE THREAD

**Issue by ShiinaRinne** [qjfoidnh/BaiduPCS-Go#248]
具体表现为:
- 使用`transfer [链接] [提取码]`或链接中自带提取码的形式无法转存文件,提示信息为 `未知错误, 错误码-62`
- 使用秒传链接可以正常转存
- 在centos8使用最新的编译版本, 链接及秒传形式均无法转存

在Windows下(v3.9.0 x64):
![image](https://user-images.githubusercontent.com/45081750/211184072-1fa367e5-6e92-4acd-abd4-0c703005d46e.png)

centos使用[e21feaf](https://github.com/qjfoidnh/BaiduPCS-Go/commit/e21feafc1e2d5bb2dee56f6518ede49bf086bfd1)的编译版本:
![image](https://user-images.githubusercontent.com/45081750/211184116-aa8161df-4fba-47a9-b14e-e3e16a3a35e7.png)

**Comment by mengzonefire** [comment]
实测3.8.8版本可以正常转存

以及秒传转存失败(代码2)的问题是由于度盘接口不稳定, 尝试多转存几次

建议作者在秒传v2接口(create接口)加入重试策略(3-4次重试即可)

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/211191845-87f2bc5c-fb1d-4df8-85b9-83f1f6e276b1.png)
我使用3.8.8版本的代码编译了一个
普通链接是获取分享项元数据错误, 秒传正常

如果方便的话,可以麻烦大佬发一个3.8.8给我吗,我的邮箱是ym@youngmoe.com @mengzonefire

**Comment by mengzonefire** [comment]
> ![image](https://user-images.githubusercontent.com/45081750/211191845-87f2bc5c-fb1d-4df8-85b9-83f1f6e276b1.png) 我使用3.8.8版本的代码编译了一个 普通链接是获取分享项元数据错误, 秒传正常
> 
> 如果方便的话,可以麻烦大佬发一个3.8.8给我吗,我的邮箱是[ym@youngmoe.com](mailto:ym@youngmoe.com) @mengzonefire

https://github.com/qjfoidnh/BaiduPCS-Go/releases/tag/v3.8.8
![Snipaste_2023-01-08_18-52-58](https://user-images.githubusercontent.com/44224240/211192180-d05b4f40-8dc1-4413-98b2-2f8cb7134d37.png)

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/211192387-d90bebe1-9f36-499a-9717-2be9e2397aed.png)
...可能是我的问题了
我测试时用到的几个链接:
```
https://pan.baidu.com/s/1jdon8C0OkqWAmQzDucRH0g?pwd=void
https://pan.baidu.com/s/1JWIMJy2hs4CmmriziN6E1Q?pwd=void
https://pan.baidu.com/s/1ttFTBF_Bk7eN6X3DE4ca0Q?pwd=void
```

**Comment by mengzonefire** [comment]
> https://pan.baidu.com/s/1jdon8C0OkqWAmQzDucRH0g?pwd=void
> https://pan.baidu.com/s/1JWIMJy2hs4CmmriziN6E1Q?pwd=void
> https://pan.baidu.com/s/1ttFTBF_Bk7eN6X3DE4ca0Q?pwd=void

测试没有问题, 试试删除 %HOMEPATH%\AppData\Roaming\BaiduPCS-Go 下的配置文件重置设置, 有可能是更改了哪项设置导致的, 不然就是账号问题了
![Snipaste_2023-01-08_19-05-26](https://user-images.githubusercontent.com/44224240/211192671-e63a710e-efcf-4455-9391-87c93a190dda.png)

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/211192853-be286ae3-32a3-4dfd-8dc4-52f135859113.png)
可能是账号问题了, 重置配置文件之后仍然是这种情况(一开始也只修改了`max_parallel`与`max_download_load`), 晚点我换个账号再试试, 今天麻烦大佬了~

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/211194238-9fb0d6e5-7f42-4c1a-ba4d-50d0b944b7a9.png)
![image](https://user-images.githubusercontent.com/45081750/211193580-843f140d-ee14-441f-a194-d0207ca3cc75.png)
我换到mac(3.8.8),在windows上也试了换个账号,都是这个问题,好怪
重启电脑, 开关代理, 切换网络环境, 切换设备, 都没能解决, 可能得等开发者有空回复了xd

**Comment by ShiinaRinne** [comment]
![D0V4MHZQ_S6(F1Y0(IX`{7A](https://user-images.githubusercontent.com/45081750/211195626-820ebb84-c5b1-4fec-9299-5baa5d70d40d.png)
![ZZPBL0626} _FKIUJHAV91C](https://user-images.githubusercontent.com/45081750/211196129-8994ef5b-824a-47dd-a63d-0e25e2d5ce2c.png)

我试着装go的环境调试看了一下, 大概是这里生成的`/share/verify`的链接有问题,
对比网页端的请求,
`app_id`和`channel`一样;
缺失`bdstoken`参数;
缺失`logid`
缺失`dp-logid`


`surl`不同, 暂时不清楚是不是每次请求都会改变;
感觉没能力继续深入挖下去了x

测试环境为windows, [e21feaf](https://github.com/qjfoidnh/BaiduPCS-Go/commit/e21feafc1e2d5bb2dee56f6518ede49bf086bfd1)版本

**Comment by mengzonefire** [comment]
今天在自己写的程序上又复现了此问题, 一通折腾后发现把
```
https://pan.baidu.com/share/verify
```
改为
```
http://pan.baidu.com/share/verify
```
就好了, 不知道百度服务端在搞什么飞机, 也可能是风控策略里有证书验证, 因为查到-62这个报错是跳验证码了:

https://www.imwxz.com/posts/508e8558.html

![Snipaste_2023-01-20_11-48-01](https://user-images.githubusercontent.com/44224240/213613649-1d3902ca-a8be-43db-8e2b-08059c87cb93.png)

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/213614966-a1609755-743f-427c-af6c-eaf886b61292.png)
在我这里改成http之后仍然是这个问题, 前三次`获取分享项元数据错误`, 后面的-62应该就是频繁访问导致的风控问题了

这个图是`获取分享项元数据错误`时的一些信息
![image](https://user-images.githubusercontent.com/45081750/213616212-476eb4c1-a763-41c1-9c81-11d86806f48a.png)

**Comment by mengzonefire** [comment]
获取分享项元数据错误应该是别的问题了, 我尝试debug一下

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/213622157-bf811c31-be69-4f51-95d4-e59777022fd8.png)
这个问题可能是试图转存自己分享的文件导致的, 之前测试时候一时间没找到别人的, 就用自己账号分享了几个, 现在试了下其他的链接可以正常转存

(没想到居然因为这个问题搞了这么长时间)

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/213622668-1c15bd31-156c-4c64-b714-ba90b3358d25.png)
这是我的主要用途, 用自己的svip账号帮群友下载文件, 再上传到群里边hhh

**Comment by mengzonefire** [comment]
原来如此, 自己的分享读出来的数据结构确实是不一样的, 同时也不需要走verify

**Comment by ShiinaRinne** [comment]
我也是点开那个链接看了一会, 突然意识到没有保存的选项, 才想着是不是这个原因xd

**Comment by ShiinaRinne** [comment]
@qjfoidnh 是否可以加一些额外的提示信息, 或者在readme里补充一下错误时候可能的情况
这次问题主要是验证码导致的`未知错误-62`
以及转存自己分享链接的`获取分享项元数据错误`
