### ISSUE TITLE
GNU Linux amd64版本無法上傳文件，輸入任何路徑都沒用

### ISSUE THREAD

**Issue by ghost** [qjfoidnh/BaiduPCS-Go#252]
如題

**Comment by nibazshab** [comment]
是不是提示 terminated by signal SIGSEGV (Address boundary error) ？我也是这个情况

**Comment by ghost** [comment]
不是提示 terminated by signal SIGSEGV (Address boundary error) ，而是提示命令幫助文本，除此以外別無他物。

**Comment by ghost** [comment]
@qjfoidnh

**Comment by ghost** [comment]
感謝回復。

**Comment by ghost** [comment]
可能是我忘記填〈要上傳到的目錄〉了。

**Comment by ghost** [comment]
我忘記填〈要上傳到的目錄〉了。
