### ISSUE TITLE
下载结束, 时间: 0s, 数据总量: 0B

### ISSUE THREAD

**Issue by gdphuang** [qjfoidnh/BaiduPCS-Go#269]
[0] 提示: 当前下载最大并发量为: 9, 下载缓存为: 65536

下载结束, 时间: 0s, 数据总量: 0B

**Comment by xinghenyinpin** [comment]
Did you solve it?

**Comment by howtofindme** [comment]
> Did you solve it?

same problem, Did you solve it?
![image](https://github.com/qjfoidnh/BaiduPCS-Go/assets/72066151/4c02e7d5-229e-4106-a54e-d812aff79787)

**Comment by chenxichenxichenxi** [comment]
整个路径用引号包住
