### ISSUE TITLE
下载带提取码的分享链接里的内容

### ISSUE THREAD

**Issue by seqyuan** [qjfoidnh/BaiduPCS-Go#27]
下载带提取码的分享链接里的内容，这个功能可以有吗？很实用的

**Comment by qjfoidnh** [comment]
开发起来比较麻烦，目前还没有计划，不过确实是个不错的功能，欢迎pull requests，哈哈

现阶段建议通过shell脚本方式组合调用转存和下载功能实现这个需求

**Comment by seqyuan** [comment]
> 开发起来比较麻烦，目前还没有计划，不过确实是个不错的功能，欢迎pull requests，哈哈
> 
> 现阶段建议通过shell脚本方式组合调用转存和下载功能实现这个需求

shell脚本的组合可以分享下吗？

**Comment by qjfoidnh** [comment]
突然发现好像不麻烦......

已经发布了，参见transfer -h

**Comment by seqyuan** [comment]
太棒了
