### ISSUE TITLE
Linux amd64 无法下载 无论下载什么都是提示  connect: connection timed out, 重试 1/3

### ISSUE THREAD

**Issue by botaoye** [qjfoidnh/BaiduPCS-Go#28]
如题

**Comment by qjfoidnh** [comment]
看上去是网络问题。建议在同一会话终端里用curl试试域名解析等是否正常

**Comment by botaoye** [comment]
> 看上去是网络问题。建议在同一会话终端里用curl试试域名解析等是否正常

网络应该没有问题,curl也没问题. 我看似乎别人的linux版本也有遇到同样问题的

**Comment by qjfoidnh** [comment]
本地没能复现，不太好排查

可能的话拿Charles之类的工具抓下包，也许能看出来问题在哪里

**Comment by botaoye** [comment]
请问抓包需要写什么?我抓包得到的response head如下,返回了{"errno":0}
![image](https://user-images.githubusercontent.com/23137816/105633627-a9179d80-5e94-11eb-96a9-ba8d3d8f0b77.png)

**Comment by qjfoidnh** [comment]
越全越好，从下载文件开始全部的request和response，summary, header, content。敏感信息记得打码

这个看不出什么东西来

**Comment by daiaji** [comment]
@suyeH 要做中间人攻击才能看到TLS加密的内容吧……
百度应该也不至于TLS都不用……
