### ISSUE TITLE
上传问题：切片超出范围

### ISSUE THREAD

**Issue by Cody292** [qjfoidnh/BaiduPCS-Go#285]
命令：
BaiduPCS-Go u --policy rsync /sk/*.mp4 K9 --norapid
日志：
panic: runtime error: slice bounds out of range [1:0]

goroutine 20 [running]:
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).deleteIndex(...)
	/home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:116
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).clearModTimeChange(0x965d068)
	/home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:183 +0x4a6
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).Search(0x965d068, 0x94b8e60)
	/home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:145 +0x35
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).prepareFile(0x94b8eb0)
	/home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_task_unit.go:77 +0xd8
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).Run(0x94b8eb0)
	/home/liu/Projects/B

**Comment by Ted-bug** [comment]
之前遇到过，直接重新安装

**Comment by Ted-bug** [comment]
> 命令： BaiduPCS-Go u --policy rsync /sk/*.mp4 K9 --norapid 日志： panic: runtime error: slice bounds out of range [1:0]
> 
> goroutine 20 [running]: github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).deleteIndex(...) /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:116 github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).clearModTimeChange(0x965d068) /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:183 +0x4a6 github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).Search(0x965d068, 0x94b8e60) /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:145 +0x35 github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).prepareFile(0x94b8eb0) /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_task_unit.go:77 +0xd8 github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).Run(0x94b8eb0) /home/liu/Projects/B

你这个问题解决了吗？我又出现了此问题，搞不定了。看源码是依据slice的长度作为循环条件，然后可能执行删除元素操作，就是在删除元素时，索引超出了

**Comment by Ted-bug** [comment]
> 

我这个问题解决了！ #244 #
