### ISSUE TITLE
【重要通知】秒传文件失败, 消息: 秒传文件: 遇到错误, 远端服务器返回错误, 代码: 2, 消息: 参数错误

### ISSUE THREAD

**Issue by chiyipianyun** [qjfoidnh/BaiduPCS-Go#290]
秒传文件失败, 消息: 秒传文件: 遇到错误, 远端服务器返回错误, 代码: 2, 消息: 参数错误

**Comment by qjfoidnh** [comment]
8.22开始因官方接口升级，原秒传链接（所有格式）失效。
新“秒传”接口所需信息在原来基础上多出了一个关键部分：在文件中随机截取4KB连续二进制并进行base64编码，从原理上来说BaiduPCS-Go及其他网页端脚本依旧可以做出适配，但“新秒传”的链接格式一定与之前不同，而且长度大大增加。

作者将继续对上传文件及导出文件所涉及的秒传功能进行适配，并尝试构造新的秒传分享格式，**但未来秒传很可能因过于繁重而被用户实质性放弃**

**Comment by qjfoidnh** [comment]
2023.8.22
已确认，新接口的部分必须字段，使用了当前登录用户的身份标识信息参与生成，这使得每个用户对本地文件生成的秒传信息与用户强绑定，无法再用于公开分享。

秒传从原理上不再可行，后续版本将下线秒传转存入口。

**Comment by haobinnan** [comment]
@qjfoidnh 不知道你是否发现，虽然提示秒传失败，但是还是秒传成功了。

**Comment by haobinnan** [comment]
> @qjfoidnh 不知道你是否发现，虽然提示秒传失败，但是还是秒传成功了。

刚才又测试了下 秒传的确不行了，前几天还行 虽然提示失败 也能秒传成功，不知道百度为什么不让秒传了，他的自带app也不提示秒传 字样了。

**Comment by haobinnan** [comment]
虽然百度客户端不提示“秒传”字样，但几个G的文件 几秒就上传成功，说明秒传功能还是有的。@qjfoidnh

**Comment by SeanHeuc** [comment]
@qjfoidnh 你好，我在维护alist的百度盘功能，之前参考过这个开源项目的代码，不巧现在百度官方升级秒传接口了，请问你有最新的协议文档吗？就是包含包括4k文件块这块逻辑的最新协议？
另外秒传的支持以后只能转向像alist这样的能提供出任意校验方法结果的服务端了，如果各个网盘的第三方客户端都愿意支持，alist可以推出专用共享链接，但这个链接必须要相应的alist服务器在工作才行。 例如alist://example_alist_server.com/share/share_id_123456,   https访问url并在header中注明需要的4k区间和对应网盘名称，就会返回 指定4k区间， 前256k 以及完整文件 的hash， 那么你这边还是可以继续使用这个链接进行秒传上传

**Comment by qjfoidnh** [comment]
> @qjfoidnh 你好，我在维护alist的百度盘功能，之前参考过这个开源项目的代码，不巧现在百度官方升级秒传接口了，请问你有最新的协议文档吗？就是包含包括4k文件块这块逻辑的最新协议？ 另外秒传的支持以后只能转向像alist这样的能提供出任意校验方法结果的服务端了，如果各个网盘的第三方客户端都愿意支持，alist可以推出专用共享链接，但这个链接必须要相应的alist服务器在工作才行。 例如alist://example_alist_server.com/share/share_id_123456, https访问url并在header中注明需要的4k区间和对应网盘名称，就会返回 指定4k区间， 前256k 以及完整文件 的hash， 那么你这边还是可以继续使用这个链接进行秒传上传

协议我肯定是没有的。。。

**Comment by SeanHeuc** [comment]
> > @qjfoidnh 你好，我在维护alist的百度盘功能，之前参考过这个开源项目的代码，不巧现在百度官方升级秒传接口了，请问你有最新的协议文档吗？就是包含包括4k文件块这块逻辑的最新协议？ 另外秒传的支持以后只能转向像alist这样的能提供出任意校验方法结果的服务端了，如果各个网盘的第三方客户端都愿意支持，alist可以推出专用共享链接，但这个链接必须要相应的alist服务器在工作才行。 例如alist://example_alist_server.com/share/share_id_123456, https访问url并在header中注明需要的4k区间和对应网盘名称，就会返回 指定4k区间， 前256k 以及完整文件 的hash， 那么你这边还是可以继续使用这个链接进行秒传上传
> 
> 协议我肯定是没有的。。。

哦 我看到你上面帖子说的很细节，如果后面有文档了希望能分享出来，谢谢

**Comment by nbihecfc** [comment]
秒传功能已恢复。

请作者大大更新token参数。

[百度网盘秒传转存助手-支持pc及移动端-永久无广告绿色版](https://greasyfork.org/zh-CN/scripts/468633-百度网盘秒传转存助手-支持pc及移动端-永久无广告绿色版/code)

660行为实现入口

accessToken获取到后，长短链秒传皆可恢复。

**Comment by reveever** [comment]
> 秒传功能已恢复。
> 
> 请作者大大更新token参数。
> 
> [百度网盘秒传转存助手-支持pc及移动端-永久无广告绿色版](https://greasyfork.org/zh-CN/scripts/468633-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%A7%92%E4%BC%A0%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8B-%E6%94%AF%E6%8C%81pc%E5%8F%8A%E7%A7%BB%E5%8A%A8%E7%AB%AF-%E6%B0%B8%E4%B9%85%E6%97%A0%E5%B9%BF%E5%91%8A%E7%BB%BF%E8%89%B2%E7%89%88/code)
> 
> 660行为实现入口
> 
> accessToken获取到后，长短链秒传皆可恢复。

有封号风险，还是实名的，最好观察观察

**Comment by qjfoidnh** [comment]
鉴于潜在的风险，先维持观察
如果一个月后仍可稳定使用，下个版本将恢复秒传转存功能

**Comment by qjfoidnh** [comment]
> 鉴于潜在的风险，先维持观察 如果一个月后仍可稳定使用，下个版本将恢复秒传转存功能

release中已发布恢复秒传的beta版, 考虑到风险暂不作为正式版发布, 请谨慎更新
