### ISSUE TITLE
关于秒传

### ISSUE THREAD

**Issue by haobinnan** [qjfoidnh/BaiduPCS-Go#292]
可能百度方面修改了接口，现在使用BaiduPCS-Go明明秒传上传成功，命令行结果返回失败。通过百度自己的pc客户端上传也不返回“秒传”，直接显示上传成功。

**Comment by pongfcnkl** [comment]
秒传已经没了
https://greasyfork.org/zh-CN/scripts/427628/feedback
https://github.com/qjfoidnh/BaiduPCS-Go/issues/290
