### ISSUE TITLE
可否生成一个便携版？

### ISSUE THREAD

**Issue by GoogleBeEvil** [qjfoidnh/BaiduPCS-Go#294]
rt，因为某些原因，经常更换电脑，能否生成一个便携版，配置文件及缓存文件都在当前目录下，这样即使放到移动硬盘里更换电脑后了，盘符繁发生变化也不用重新登陆，重新配置。

**Comment by pongfcnkl** [comment]
可通过设置环境变量 BAIDUPCS_GO_CONFIG_DIR, 指定配置文件存放的目录.
然后只需要这样写个bat就行了
![截图_20230824155502](https://github.com/qjfoidnh/BaiduPCS-Go/assets/24273319/67cda4e9-4de7-4b1f-b516-631600d763b9)

**Comment by ghost** [comment]
直接在baidupcs-Go.exe文件所在目录下， 建立 pcs_config.json 空文件， 然后点击baidupcs-Go.exe运行就行了
