### ISSUE TITLE
上个版本更新前后，上传文件全部失败，本地只用来上传文件，从不下载，更新和重新登录账号已经试过了，都不行

### ISSUE THREAD

**Issue by MyBirdVery6** [qjfoidnh/BaiduPCS-Go#295]
goroutine 6 [running]:
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).deleteIndex(...)

        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:116
[0] 提示: 当前上传单个文件最大并发量为: 4, 最大同时上传文件数为: 4github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).clearModTimeChange(
0xc000341920)
        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go[1] 加入上传队列: E:/ABCI/ABC-Task/BaiduPCS-Go_Backup.cmd:
183 +0x4c8
[2] 加入上传队列: E:/AOMEI/Dnn-Task/DeleteBackup.cmdgithub.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).Search
(0xc000341920, 0xc0001fe630[2] 准备上传: E:/ABC/ABC-Task/DeleteBackup.cmd)

        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:145[1] 准备上传: E:/ABC/ABC-Task/BaiduPCS-Go_Backup.cmd +
0x39
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).prepareFile(0xc000252280)
        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_task_unit.go:79 +0xeb
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).Run(0xc000252280)
        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_task_unit.go:380 +0x1f3
github.com/qjfoidnh/BaiduPCS-Go/pcsutil/taskframework.(*TaskExecutor).Execute.func1(0xc000368678)
        /home/liu/Projects/BaiduPCS-Go/pcsutil/taskframework/executor.go:94 +0x72
created by github.com/qjfoidnh/BaiduPCS-Go/pcsutil/taskframework.(*TaskExecutor).Execute
        /home/liu/Projects/BaiduPCS-Go/pcsutil/taskframework/executor.go:91 +0xd8

**Comment by MyBirdVery6** [comment]
之前使用的是 bduss会出现这个问题，更换cookies后，发现问题解决

**Comment by Ted-bug** [comment]
#244 我的是这样子
