### ISSUE TITLE
func (pcs *BaiduPCS) PrepareUploadSuperfile2 方法调用问题

### ISSUE THREAD

**Issue by Qoiuy** [qjfoidnh/BaiduPCS-Go#296]
你好。
背景：
我最近在用这个项目写个小脚本所以关注了本项目。
我的目的是上传文件 没有其他需求。（因为项目中用了协程加速，所以参考本项目）

问题：
我在看项目代码的时候 简单搜索了一下 superfile2，发现项目内是由支持 开放平台接口的方法（BaiduPCS.PrepareUploadSuperfile2）。
但是在项目的实际运行时却没有 被调用。 为什么 是因为token的原因吗？ 还是？

描述：
我看到的代码逻辑如下 （我重点关注了上传文件接口。我知道有预上传接口 和合并接口 ）

main() ====>  pcscommand.RunUpload() ====>  UploadTaskUnit.Run()====>   UploadTaskUnit.upload() ====>MultiUploader.Execute() => MultiUploader.upload() => multiUpload.TmpFile()
====> pcs.UploadTmpFile()  ====>  BaiduPCS.PrepareUploadTmpFile()

最后 BaiduPCS.PrepareUploadTmpFile()方法中
请求的是 /rest/2.0/pcs/file?method=upload

我在开发平台文档上看到的接口是
/rest/2.0/pcs/superfile2?method=upload&access_token

**Comment by Qoiuy** [comment]
我想问的是 是token适配不方便（因为我看授权方式大多是BDUSS）？
还是说这个接口响应慢？不适合该项目？
还是说啥原因？ 有点懵的。

我最开始以为项目会适配开放平台接口的,然后都去申请了一个开发平台的应用...最后发现用不了 有些尴尬.

**Comment by Ted-bug** [comment]
> 我想问的是 是token适配不方便（因为我看授权方式大多是BDUSS）？ 还是说这个接口响应慢？不适合该项目？ 还是说啥原因？ 有点懵的。
> 
> 我最开始以为项目会适配开放平台接口的,然后都去申请了一个开发平台的应用...最后发现用不了 有些尴尬.

开放平台主要是开发第三方应用，所以需要申请、授权。这个项目个人感觉还是偏向于个人使用（没有那么多的授权过程）

**Comment by Qoiuy** [comment]
> 

我的理解 虽然开发平台是第三方应用， 但比较是官方的  被封禁概率小吧.

**Comment by Qoiuy** [comment]
https://github.com/qjfoidnh/BaiduPCS-Go/issues/296#issuecomment-1709762846
我的理解是
虽然第三方应用比较麻烦 ，但毕竟是官方的 ，被封禁的概率会很小吧?

**Comment by Qoiuy** [comment]
> > 我想问的是 是token适配不方便（因为我看授权方式大多是BDUSS）？ 还是说这个接口响应慢？不适合该项目？ 还是说啥原因？ 有点懵的。
> > 我最开始以为项目会适配开放平台接口的,然后都去申请了一个开发平台的应用...最后发现用不了 有些尴尬.
> 
> 开放平台主要是开发第三方应用，所以需要申请、授权。这个项目个人感觉还是偏向于个人使用（没有那么多的授权过程）

我的理解是
虽然第三方应用比较麻烦 ，但毕竟是官方的 ，被封禁的概率会很小吧?

**Comment by Ted-bug** [comment]
> [#296 (comment)](https://github.com/qjfoidnh/BaiduPCS-Go/issues/296#issuecomment-1709762846) 我的理解是 虽然第三方应用比较麻烦 ，但毕竟是官方的 ，被封禁的概率会很小吧?

那服务需要付费，但是官网没写资费

**Comment by Qoiuy** [comment]
> > [#296 (comment)](https://github.com/qjfoidnh/BaiduPCS-Go/issues/296#issuecomment-1709762846) 我的理解是 虽然第三方应用比较麻烦 ，但毕竟是官方的 ，被封禁的概率会很小吧?
> 
> 那服务需要付费，但是官网没写资费

额.. 不需要付费吧?你指的是创建应用之后 调用接口需要付费？
还是？ 
开放平台的盈利模式不是从开发者手中取钱吧. （因为开发者可以增加用户的使用量） <=我没理解错吧

**Comment by qjfoidnh** [comment]
除了无法避开的情况（比如最新的秒传转存），项目会尽量避免使用openapi
openapi会很大增加使用门槛，而且access_token生命周期比BDUSS+STOKEN短的多
现在没有证据表明pcs接口与openapi在封禁概率上有显著差别

**Comment by Qoiuy** [comment]
> 除了无法避开的情况（比如最新的秒传转存），项目会尽量避免使用openapi openapi会很大增加使用门槛，而且access_token生命周期比BDUSS+STOKEN短的多 现在没有证据表明pcs接口与openapi在封禁概率上有显著差别

有最后一句我就懂了 嘿嘿😁
多谢指点
