### ISSUE TITLE
arm64版: 任何网络操作网络错误

### ISSUE THREAD

**Issue by torappinfo** [qjfoidnh/BaiduPCS-Go#3]
PC版，原版的arm64版一切正常。运行于android termux下：

获取目录下的文件列表: 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=266719&by=name&limit=0-2147483647&method=list&order=asc&path=%2Fapps%2Flin1118: lookup pcs.baidu.com on [::1]:53: read udp [::1]:4
8970->[::1]:53: read: connection refused

**Comment by torappinfo** [comment]
可能版本编译设置不对？

**Comment by torappinfo** [comment]
linux amd64版一切正常。

**Comment by pongfcnkl** [comment]
安卓需要重新编译，不能用Linux的arm64位

**Comment by pongfcnkl** [comment]
这个是作者网站上archive下来的教程，要用Linux或者macos
https://web.archive.org/web/20190830041727/http://www.iikira.com/2017/08/09/golang-compile-jc-2/
