### ISSUE TITLE
关于网盘的下载问题

### ISSUE THREAD

**Issue by wrwe3888** [qjfoidnh/BaiduPCS-Go#30]
假如网盘里有20万个文件，这些文件放在若干个文件夹里。
我要下载的1000份文件，处在不同的文件夹中。

我之前的下载步骤是：
（1）导出一份百度网盘的目录清单。
（2）在mysql中逐一查询每个文件的路径。
（3）用baidupcs-go把这些文件复制到一个指定的文件夹中。
（4）用百度网盘直接下载，因为我是网盘会员，下载速度快。

之所以不用baidupcs-go的download命令，
因为觉得那是用baidupcs在下载，万一因此被百度封号，就不划算了。
但是这样下载又很麻烦。

所以我想问的是：
直接用baidupcs-go下载，安全吗？
换句话说，我的麻烦下载方式，有必要吗？

十分感谢！

**Comment by qjfoidnh** [comment]
安全的，baidupcs-go的下载接口与手机客户端一致。作者本人每天都有下载行为，已稳定使用数月。
升级到最新版，按照README里建议设置下载线程数，不要设置过大。

**Comment by wrwe3888** [comment]
【1】我用上个月GangZhuo/BaiduPCS的版本，下载速度50KB都没有，而我用百度网盘客户端下载，速度10M。不知道你下载的速度如何？
【2】如果是手机客户端的接口的话，那是不是下载量大的话，就不太方便用这baidupcs了？

**Comment by qjfoidnh** [comment]
【1】速度与客户端基本相当（按照建议线程数）
【2】不是
