### ISSUE TITLE
手机号换绑后，登录时验证手机号登录异常

### ISSUE THREAD

**Issue by stark-sim** [qjfoidnh/BaiduPCS-Go#301]
![image](https://github.com/qjfoidnh/BaiduPCS-Go/assets/67146986/9929f858-5146-4ed0-9319-3722f9ac1881)

**Comment by stark-sim** [comment]
版本 3.9.4 linux-amd64

**Comment by i-Libra** [comment]
同样遇到这个问题。

**Comment by qjfoidnh** [comment]
将在下个版本修复，但仍建议使用cookie或bduss方式登录，账号登录方式后续可能不再支持
