### ISSUE TITLE
上传目录时，偶尔出现严重错误： fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by hqwu-github** [qjfoidnh/BaiduPCS-Go#302]
目录中有很多文件，当上传该目录时，偶尔出现严重错误： fatal error: sync: unlock of unlocked mutex
具体如下：

[158894]准备上传: /数据备份/wh
fatal error: sync: unlock of unlocked mutex
goroutine 183823 [running]:runtime.throw(foxa1e72e?，0x99e440?})usr/lib/go-1.18/src/runtime/panic.go:992 +0x71
sync.throw([oxa1e72e?，xc03foadbfo?])usr/lib/go-1.18/src/runtime/panicgo:978 +0x1e fp-0xc0c5915ac@ sp-0

**Comment by hqwu-github** [comment]
如下有一个出现类似错误的网页，请看是否有借鉴意义：

https://segmentfault.com/q/1010000042869428/a-1020000042870207

**Comment by qjfoidnh** [comment]
请问该错误出现的场景里，有提示过 “秒传失败, 开始上传文件...” 吗？
