### ISSUE TITLE
错误代码: 50052, 消息: 系统繁忙，请稍候再试(50052)

### ISSUE THREAD

**Issue by korin5** [qjfoidnh/BaiduPCS-Go#305]
输入账号密码之后的报错

**Comment by qjfoidnh** [comment]
账号密码登录后续不保障可用，建议使用cookies登录

**Comment by glxay** [comment]
同问

**Comment by tsdcz** [comment]
同问

**Comment by korin5** [comment]
> 同问

这里使用cookies登录就成功了

**Comment by korin5** [comment]
> 同问

建议使用cookies登录

**Comment by kevinh458** [comment]
> > 同问
> 
> 建议使用cookies登录

用cookie登录闪退有碰到吗

**Comment by korin5** [comment]
> 用cookie登录闪退有碰到吗

我去年用的时候没碰到

**Comment by kevinh458** [comment]
> > 用cookie登录闪退有碰到吗
> 
> 我去年用的时候没碰到

我解决了。cookie=的时候忘了加引号了

**Comment by zhoushican** [comment]
如何使用cookie进行登录呢？

**Comment by e71828** [comment]
https://github.com/PeterDing/BaiduPCS-Py?tab=readme-ov-file#%E6%B7%BB%E5%8A%A0%E7%94%A8%E6%88%B7
