### ISSUE TITLE
关于上传速度问题

### ISSUE THREAD

**Issue by nazhendenb** [qjfoidnh/BaiduPCS-Go#31]
本人从2020年1月开始使用BaiduPCS-Go，使用海外Linux系统VPS+录像脚本 [liverecord](https://github.com/lovezzzxxx/liverecord) 录制ASMR直播并备份到百度网盘

从一开始的谷歌云，到后来的Veesp，contabo，腾讯云香港地区，亚马逊aws，vultr。 我使用过多家运营商的VPS，除了腾讯云香港的上传速度可以接近满速(然而出口带宽只有30Mbps)，其他各家VPS上传速度均不到1MB/s 。（这几家都是大厂，传谷歌云能跑到20+MB/s）

前一阵子看到有新大佬接手了这个项目，就想到了这个问题，比起解决问题本身，我还是更想知道上传速度慢是什么原因，这个问题困扰了我有将近一年了，我可是尊贵的(划掉)SVIP

这个问题对我的影响也不算大，因为小姐姐们都是晚上播的，通宵上传到第二天再去取回也还行，就算因为网络抽风录制的时候断流了，用自己写的小型shell脚本重新录一遍(就算把两段拼起来也还是会少几秒钟,还不如重新录)也能补回来

不知道大佬有没有使用海外VPS上传的经验，我尝试过把 max_upload_parallel 从4调到10，也没有改善
如果是除了腾讯云香港的其他几家的线路对中国大陆不友好，我就继续尝试别的VPS，如果说是百度对海外有限速+和TX有PY，我就只能死心了

顺便问一下上传接口用的也是手机客户端吗？[#30](https://github.com/qjfoidnh/BaiduPCS-Go/issues/30)

**Comment by qjfoidnh** [comment]
上传接口跟手机客户端不同，跟网页也不同，是老的pcs接口，因为还能用就一直没去管

海外VPS没做过实验，纯看描述很像是线路问题，经测试上传服务器是没有海外节点的，所以理论上GIA等高端线路和临近节点（日韩）速度会更好，就是贵

**Comment by nazhendenb** [comment]
> 上传接口跟手机客户端不同，跟网页也不同，是老的pcs接口，因为还能用就一直没去管
> 
> 海外VPS没做过实验，纯看描述很像是线路问题，经测试上传服务器是没有海外节点的，所以理论上GIA等高端线路和临近节点（日韩）速度会更好，就是贵

我哭了，一人血书求求大佬把换接口加入TODO

**Comment by nazhendenb** [comment]
另外还发现一个小问题， config配置页面的"建议值"往下沉了一行，在Windows下也有同样的问题
![image](https://user-images.githubusercontent.com/36919867/105629396-baa17b00-5e7d-11eb-8b53-07430993b1d5.png)

**Comment by nazhendenb** [comment]
> 上传接口跟手机客户端不同，跟网页也不同，是老的pcs接口，因为还能用就一直没去管
> 
> 海外VPS没做过实验，纯看描述很像是线路问题，经测试上传服务器是没有海外节点的，所以理论上GIA等高端线路和临近节点（日韩）速度会更好，就是贵

我录的网站是niconico，每次都是用日本的机子，不然老是断流（辣鸡nico至今最高画质还是720P）
换了个日本软银的机房，这线路总不算太差吧。本地ping值两位数，但是上传速度仍然没有改善，估计还得跑一个通宵
![image](https://user-images.githubusercontent.com/36919867/105633454-a2d4f180-5e93-11eb-9402-f5d091d28261.png)

![image](https://user-images.githubusercontent.com/36919867/105633404-54275780-5e93-11eb-96db-8d569491f77c.png)
![image](https://user-images.githubusercontent.com/36919867/105633376-204c3200-5e93-11eb-9fb7-7b232e453bf8.png)

**Comment by qjfoidnh** [comment]
config那个是第三方包的问题，对付看吧（误）

我建议可以这样：在你上传用的VPS上搭个梯子，然后用自己PC也好，手机也好翻到上面，再用官方客户端上传看看速度，虽然不会很准确（多了个去程），但大概能分析出是线路问题还是pcs上传接口问题。
当然如果有个外国友人帮忙测试就更好了

**Comment by pongfcnkl** [comment]
在国外VPS上传为什么不用国外的网盘？
比如可以白嫖OneDrive的e5订阅

**Comment by nazhendenb** [comment]
> 在国外VPS上传为什么不用国外的网盘？
> 比如可以白嫖OneDrive的e5订阅

因为群友都是懒狗，只会用百度

**Comment by pongfcnkl** [comment]
> 
> 
> > 在国外VPS上传为什么不用国外的网盘？
> > 比如可以白嫖OneDrive的e5订阅
> 
> 因为群友都是懒狗，只会用百度

用OneDrive中转一下，在本地上传百度网盘

**Comment by nazhendenb** [comment]
> config那个是第三方包的问题，对付看吧（误）
> 
> 我建议可以这样：在你上传用的VPS上搭个梯子，然后用自己PC也好，手机也好翻到上面，再用官方客户端上传看看速度，虽然不会很准确（多了个去程），但大概能分析出是线路问题还是pcs上传接口问题。
> 当然如果有个外国友人帮忙测试就更好了
搭了个l2tp(之前搭V2ray开全局查IP还是在境内的)，速度稳定1.4MB，（家宽上传最高只有3MB），3GB的文件预计50分钟
![image](https://user-images.githubusercontent.com/36919867/105658154-eade2d80-5f00-11eb-91dd-3cb116692a74.png)

![image](https://user-images.githubusercontent.com/36919867/105658280-2a0c7e80-5f01-11eb-9d41-d47c7b2ec71b.png)

#########################
对比PCS的接口，昨天晚上8点多挂上，今天凌晨1点才传好，平均速度130K
![image](https://user-images.githubusercontent.com/36919867/105658016-976bdf80-5f00-11eb-891a-2dd7340cd354.png)

**Comment by qjfoidnh** [comment]
这样接口的嫌疑就很大了

下个版本更新

**Comment by nazhendenb** [comment]
> 这样接口的嫌疑就很大了
> 
> 下个版本更新

不过要测试线路问题的话直接把VPS重装成Windows系统用官方客户端岂不是更方便（

**Comment by nazhendenb** [comment]
> > > 在国外VPS上传为什么不用国外的网盘？
> > > 比如可以白嫖OneDrive的e5订阅
> > 
> > 
> > 因为群友都是懒狗，只会用百度
> 
> 用OneDrive中转一下，在本地上传百度网盘

学校11点断电断网，自己的电脑24小时不关机也不现实，而且我也是懒狗，宁可慢点也不愿意多一个流程

**Comment by techoc** [comment]
> > 在国外VPS上传为什么不用国外的网盘？
> > 比如可以白嫖OneDrive的e5订阅
> 
> 因为群友都是懒狗，只会用百度

我有个朋友他也想进群😂

**Comment by nazhendenb** [comment]
> > > 在国外VPS上传为什么不用国外的网盘？
> > > 比如可以白嫖OneDrive的e5订阅
> > 
> > 
> > 因为群友都是懒狗，只会用百度
> 
> 我有个朋友他也想进群😂

![image](https://user-images.githubusercontent.com/36919867/105710968-d591ef00-5f52-11eb-952b-1cb1b345fb14.png)

**Comment by qjfoidnh** [comment]
> 本人从2020年1月开始使用BaiduPCS-Go，使用海外Linux系统VPS+录像脚本 [liverecord](https://github.com/lovezzzxxx/liverecord) 录制ASMR直播并备份到百度网盘
> 
> 从一开始的谷歌云，到后来的Veesp，contabo，腾讯云香港地区，亚马逊aws，vultr。 我使用过多家运营商的VPS，除了腾讯云香港的上传速度可以接近满速(然而出口带宽只有30Mbps)，其他各家VPS上传速度均不到1MB/s 。（这几家都是大厂，传谷歌云能跑到20+MB/s）
> 
> 前一阵子看到有新大佬接手了这个项目，就想到了这个问题，比起解决问题本身，我还是更想知道上传速度慢是什么原因，这个问题困扰了我有将近一年了，我可是尊贵的(划掉)SVIP
> 
> 这个问题对我的影响也不算大，因为小姐姐们都是晚上播的，通宵上传到第二天再去取回也还行，就算因为网络抽风录制的时候断流了，用自己写的小型shell脚本重新录一遍(就算把两段拼起来也还是会少几秒钟,还不如重新录)也能补回来
> 
> 不知道大佬有没有使用海外VPS上传的经验，我尝试过把 max_upload_parallel 从4调到10，也没有改善
> 如果是除了腾讯云香港的其他几家的线路对中国大陆不友好，我就继续尝试别的VPS，如果说是百度对海外有限速+和TX有PY，我就只能死心了
> 
> 顺便问一下上传接口用的也是手机客户端吗？[#30](https://github.com/qjfoidnh/BaiduPCS-Go/issues/30)

3.7.8版优化了一下上传逻辑，对海外用户应该有相当明显的效果，可以试试。

**Comment by nazhendenb** [comment]
> 3.7.8版优化了一下上传逻辑，对海外用户应该有相当明显的效果，可以试试。
![image](https://user-images.githubusercontent.com/36919867/111874086-7a1e3380-89ce-11eb-955e-333f163293ab.png)

这是美国的流量机，SSH输入都很卡，线路相对来说比较差。 平均速度能有个2-300K，比以前用aws的时候快了几乎一倍，确实有提升。
果然还是线路的问题，我2月份就把环境都搬到了日本软银线路的VPS上，用3.7.5版本的就能跑到40M+（带宽是500Mbps） 。
不管是流量机还是软银机，c4域名是最快的，很神奇。
大佬更新的好快，赞美大佬
顺便问一下修复被封的链接大概是什么原理？

**Comment by nazhendenb** [comment]
上述只是根据以往经验的猜测，接下来我会用流量机对每个域名进行上传测试，届时会反馈测试结果

**Comment by qjfoidnh** [comment]
原理挺简单，就是对秒传链接里的md5字母随机大小写化......

也不知道为啥就能生效，只能猜测跟后台实现的屏蔽文件检测机制有关

**Comment by nazhendenb** [comment]
> 原理挺简单，就是对秒传链接里的md5字母随机大小写化......
> 
> 也不知道为啥就能生效，只能猜测跟后台实现的屏蔽文件检测机制有关

前几天看到老方丈的JS脚本下面也有讨论，不知道你的参考地址是不是他的仓库。。
关于这点我倒是想起来用QQ机器人的时候，群聊图片的URL里文件名都是大写，本地缓存的.image文件又变成了小写

**Comment by nazhendenb** [comment]
![image](https://user-images.githubusercontent.com/36919867/111889223-8b8f2c00-8a1e-11eb-8136-4c80be36ddb8.png)
![image](https://user-images.githubusercontent.com/36919867/111889902-ac0bb600-8a1f-11eb-83ec-7a5b486fdc52.png)
![image](https://user-images.githubusercontent.com/36919867/111889907-af06a680-8a1f-11eb-9470-7c7ab3912368.png)
![image](https://user-images.githubusercontent.com/36919867/111889911-b2019700-8a1f-11eb-82ee-6a9cee51287e.png)
![image](https://user-images.githubusercontent.com/36919867/111889914-b3cb5a80-8a1f-11eb-9dc5-3edd2e912c89.png)
![image](https://user-images.githubusercontent.com/36919867/111889915-b62db480-8a1f-11eb-8b6a-cd9eef4e8fae.png)
![image](https://user-images.githubusercontent.com/36919867/111889939-e2e1cc00-8a1f-11eb-8de9-38005f5be40f.png)


测完了，第一张图是昨晚测的C4域名，平均只有300K。
但是今天早上测试直接起飞了呀，c2 c3 c4 c5 d 均有优秀表现。
 默认的域名我记得是pcs.baidu.com，昨天测了一下速度太慢我就CTRL+C了，不过今天早上速度也有很大提升，但是最后卡在了99%，很蛋疼
最后是c.pcs.baidu.com，速度显示仍然只有300K，还没传完，晚点贴图
本次测试的量不算大，速度可能和上传时间段有关系（白天/夜晚），不过已经有很大改善了
最终我的结论只有一个字：您！！

**Comment by qjfoidnh** [comment]
对，就是老方丈的那个脚本，据老方丈说他也是碰巧在另一个网站提供的功能中发现这个技巧的。

这次上传提速与其说是优化，倒不如说是修了一个bug，这个bug国内使用者不容易发现，但在延迟高的海外环境会凸显出来，尤其是多线程传大文件时，要不是前两天有人反馈了一个连接数爆炸的问题我还发现不了。
