### ISSUE TITLE
列出已分享文件/目录时，显示内容有误

### ISSUE THREAD

**Issue by nazhendenb** [qjfoidnh/BaiduPCS-Go#32]
版本为3.7.3 windows x64  
在Ubuntu 18系统下测试也有同样问题

如图，经浏览器测试，除了第二个是真的过期以外，其余均未过期
初步观察发现：分享的文件可以正常显示，分享的目录无法显示提取码，并且状态会显示为"已过期"
![image](https://user-images.githubusercontent.com/36919867/105663609-a907b400-5f0d-11eb-9d9e-967a06ede48e.png)
![image](https://user-images.githubusercontent.com/36919867/105663638-bb81ed80-5f0d-11eb-80d2-1a1a1100d5de.png)

**Comment by nazhendenb** [comment]
补个图，新创建的目录也是一样的问题
![image](https://user-images.githubusercontent.com/36919867/105663934-5ed30280-5f0e-11eb-984c-14cabcba55de.png)
![image](https://user-images.githubusercontent.com/36919867/105663942-6397b680-5f0e-11eb-8a81-95df78aa6799.png)

**Comment by qjfoidnh** [comment]
上次更新改的逻辑，看来是改出bug了，下个版本一并带上吧
