### ISSUE TITLE
上传文件失败, 分片上传—文件分片及上传: 网络错误, http 响应错误, 403 Forbidden, 重试 2/3

### ISSUE THREAD

**Issue by nazhendenb** [qjfoidnh/BaiduPCS-Go#34]
昨天晚上日本的机子403了，我也没多想，以为重试失败过多给我ban了(因为白天我给录播脚本加了个新功能)。
今天在3台机子上测试过，全403了感觉不对劲，是不是百度改什么东西了(悲
3台机子分别为日本的linux 香港的linux 本地的Windows
![image](https://user-images.githubusercontent.com/36919867/106213043-d488e800-6206-11eb-83d5-028dd063fd05.png)

**Comment by nazhendenb** [comment]
顺带一提版本均为3.7.3，之前下载功能不能用，我以为退回个版本就好了，所以目录里有3.7.1的压缩包。

后来发现是我参数错了， 我以为第二个参数是本地保存目录，结果就是程序把根目录添加进队列里，当然会卡住

**Comment by nazhendenb** [comment]
换了个号发现能上传了，我印象里也没做过滥用的事（悲
昨天唯一和平时不同的地方就是用vultr开了个日本的Windows机子，登陆了BaiduPCS-Go，想看看上传到底是线路问题还是接口问题，测完就删机了
官方客户端也还能用，APP也没有账号异常之类的消息，我哭了
![image](https://user-images.githubusercontent.com/36919867/106213891-a1dfef00-6208-11eb-98b5-aa1b2a5a38a8.png)

**Comment by qjfoidnh** [comment]
哎，新的上传接口跟现在PCSGo里的差别好大噢，本来以为可以改改函数就糊弄过去的。

再鸽一段时间好了╮(￣▽￣)╭

**Comment by nazhendenb** [comment]
![image](https://user-images.githubusercontent.com/36919867/106229133-e0d16d00-6227-11eb-9ff8-59450eff7a3a.png)
正好大号也快塞满了，换小号（无SVIP）撑一段时间（逃

**Comment by nazhendenb** [comment]
> 哎，新的上传接口跟现在PCSGo里的差别好大噢，本来以为可以改改函数就糊弄过去的。
> 
> 再鸽一段时间好了╮(￣▽￣)╭

假设我传一半不想传了，直接取消就好了吗？有没有缓存文件之类的需要删除 （我看他可以断点续传就随便猜的

**Comment by qjfoidnh** [comment]
目前读明白的部分来看，它只会记录已经上传的块编号，文件指针偏移量啥的

**Comment by qjfoidnh** [comment]
我发现可能想复杂了。。。接口可能并不是关键，上传服务器的域名才是。
你下这个版本试试，看速度有没有明显改善
https://wwe.lanzous.com/ijnqql3w5xe

**Comment by nazhendenb** [comment]
![image](https://user-images.githubusercontent.com/36919867/106367301-78e06b00-637c-11eb-8fb7-72b700e32a6f.png)
![image](https://user-images.githubusercontent.com/36919867/106367302-7b42c500-637c-11eb-9a72-5b5392758889.png)
 分别为vultr新加坡和之前搭过代理的日本软银，平均速度分别为230KB/s和9MB/s，初步判断是有所改善，但也不大。 要出门了，晚点再做更多的测试
软银的速度快是快，但流量是上下行都算的，钱包有点顶不住

**Comment by nazhendenb** [comment]
更新： 
1. 早在27号，我发现软银线路的机子上传速度突然变快，11分钟上传700G，平均速度6-7MB吧。但是想到大佬还在施工就没有打扰
所以结论是换完域名有提升，但是提升不大
![image](https://user-images.githubusercontent.com/36919867/106375647-c5519800-63c8-11eb-8987-72f37504e8fc.png)
![image](https://user-images.githubusercontent.com/36919867/106375614-89b6ce00-63c8-11eb-9c42-eb768293542c.png)

**Comment by nazhendenb** [comment]
2. 之前测试的时候，只有使用 --bduss "123" --stoken "234" （第一次是偷懒没有指定stoken，第二次是使用了 -bduss 123 -stoken 234）的时候才能上传， 前两种方式登录时，报错显示域名错误之类的，早上急着出门，测完就删机了，没有保存截图，现在也没法复现了。。。很尴尬

vultr 速度依旧感人
![image](https://user-images.githubusercontent.com/36919867/106376284-c08fe280-63ce-11eb-971d-90e3e012f5c5.png)

**Comment by qjfoidnh** [comment]
https://wwe.lanzous.com/iU2V7l57ouh
这个测试版跟刚发布的3.7.4比除了能修改上传服务器外，还用了新的上传接口（细节还不太完善，但确实是手机客户端的接口）
可用服务器列表见README.md
可以比较一下同线路同pcs服务器同并发下速度有无差别

另外提示stoken缺失的问题应该是解决了

**Comment by nazhendenb** [comment]
> https://wwe.lanzous.com/iU2V7l57ouh
> 这个测试版跟刚发布的3.7.4比除了能修改上传服务器外，还用了新的上传接口（细节还不太完善，但确实是手机客户端的接口）
> 可用服务器列表见README.md
> 可以比较一下同线路同pcs服务器同并发下速度有无差别
> 
> 另外提示stoken缺失的问题应该是解决了

**1.stoken缺失的问题仍然存在**
![image](https://user-images.githubusercontent.com/36919867/106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6.png)

**2. 试了c5域名，前2分钟: 基本维持3-4MB，很少会降到1M以下。2分钟之后：没上过300K**
![image](https://user-images.githubusercontent.com/36919867/106404591-20899600-646e-11eb-82a2-7f6d917e815b.png)

**3.速度慢下来之后，我使用CTRL+C中止，然后更换域名，此时上传进度条会直接拉满，然后开始无限400 bad request**
![image](https://user-images.githubusercontent.com/36919867/106404719-9b52b100-646e-11eb-9a10-c1c33d96b44b.png)

**4.能不能把检测能否秒传之后打印的一长串文件信息给关掉？做成个开关可以手动选择是否显示就行**
![image](https://user-images.githubusercontent.com/36919867/106404773-bfae8d80-646e-11eb-97b5-48a720d643a3.png)

最后，赞美大佬

**Comment by qjfoidnh** [comment]
那stoken我也不造是啥情况了，对付看吧......

新接口也这样的话那应该跟具体接口关系不大了，单文件并发数调高点试试？我一般都十几。另外这个实时速度计算不太准（还没发现怎么修），直接用下载总时间算准一点

域名中途更换确实会出问题，单个文件不能上传到多个服务器

这里提供的是一个工程版，有一些调试还开着。你可以去下3.7.4，如果我推断不错上传表现应该差不多

**Comment by nazhendenb** [comment]
> 那stoken我也不造是啥情况了，对付看吧......
> 
> 新接口也这样的话那应该跟具体接口关系不大了，单文件并发数调高点试试？我一般都十几
> 
> 域名中途更换确实会出问题，单个文件不能上传到多个服务器
> 
> 这里提供的是一个工程版，有一些调试还开着。你可以去下3.7.4，如果我推断不错上传表现应该差不多

草，原来400是我操作不当

**Comment by pongfcnkl** [comment]
> **1.stoken缺失的问题仍然存在**
> ![image](https://user-images.githubusercontent.com/36919867/106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6.png)
> 


没写=？
![Screenshot_2021-02-01 106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6 png（PNG 图像，1087x173 像素）](https://user-images.githubusercontent.com/24273319/106439083-3f118080-64b2-11eb-9fb3-a629918e4a74.png)

**Comment by qjfoidnh** [comment]
> > **1.stoken缺失的问题仍然存在**
> > ![image](https://user-images.githubusercontent.com/36919867/106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6.png)
> 
> 没写=？
> ![Screenshot_2021-02-01 106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6 png（PNG 图像，1087x173 像素）](https://user-images.githubusercontent.com/24273319/106439083-3f118080-64b2-11eb-9fb3-a629918e4a74.png)

那个不影响，只是参数输入风格的问题。

**Comment by nazhendenb** [comment]
> > > **1.stoken缺失的问题仍然存在**
> > > ![image](https://user-images.githubusercontent.com/36919867/106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6.png)
> > 
> > 
> > 没写=？
> > ![Screenshot_2021-02-01 106404636-4c0c8080-646e-11eb-9b22-1f5e061abcf6 png（PNG 图像，1087x173 像素）](https://user-images.githubusercontent.com/24273319/106439083-3f118080-64b2-11eb-9fb3-a629918e4a74.png)
> 
> 那个不影响，只是参数输入风格的问题。

两个减号，不需要写。
我bduss也没写

**Comment by nazhendenb** [comment]
![image](https://user-images.githubusercontent.com/36919867/106442204-f52a9980-64b5-11eb-825f-d703790a065b.png)
![image](https://user-images.githubusercontent.com/36919867/106442211-f6f45d00-64b5-11eb-8b8e-d55db344069a.png)
![image](https://user-images.githubusercontent.com/36919867/106442236-fe1b6b00-64b5-11eb-9bca-0a36d65992e4.png)
![image](https://user-images.githubusercontent.com/36919867/106442245-ffe52e80-64b5-11eb-84a0-9bce9c29f498.png)

aws lightsail , 东京的机子，测了四个域名，c4 c3 c 这三个域名平均速度有1M  


并且我发现线路的锅还挺大，下图为vultr日本机房
![image](https://user-images.githubusercontent.com/36919867/106444976-6ae43480-64b9-11eb-831f-410e0c2f71c7.png)

准备换韩国的机子试试。
 绕来绕去还是只有30M出口带宽的腾讯云跑得最快（

感谢大佬， 虽然速度仍不理想，但已经比传一个通宵好太多了

**Comment by nazhendenb** [comment]
![image](https://user-images.githubusercontent.com/36919867/106456751-ed282500-64c8-11eb-9c72-3a159ef620c2.png)
![image](https://user-images.githubusercontent.com/36919867/106456762-f1ecd900-64c8-11eb-8630-18df140787d9.png)
更新： 又测了vultr 新加坡和韩国，域名为c2。 平均速度分别为2.6M和16M。  貌似只有日本线路拉跨。
但是我一开始用谷歌云和veesp的时候，地区分别是美国和俄罗斯。  我开始怀疑人生了
再次赞美大佬，不明觉厉

**Comment by nazhendenb** [comment]
下个月准备把录播的机子迁到韩国看看，手机客户端接口的工程还是希望大佬继续开发

![image](https://i.postimg.cc/XJMgrwVr/QQ-20210201201631.gif)
