### ISSUE TITLE
下载速度被限制

### ISSUE THREAD

**Issue by Xuxue1** [qjfoidnh/BaiduPCS-Go#340]
下载速度被限制在了100kb\s 以内

**Comment by BlueSkyXN** [comment]
> 下载速度被限制在了100kb\s 以内

打电话给110问一下银行卡余额不足怎么购物

**Comment by BlueSkyXN** [comment]
> 下载速度被限制在了100kb\s 以内

百度本身有限速策略，撸多了就限

**Comment by Xuxue1** [comment]
@BlueSkyXN 重度使用者，开的svip10。用了有半年, 最近刚出现的这个问题。 不过我后来找到原因解决了

**Comment by BlueSkyXN** [comment]
> @BlueSkyXN 重度使用者，开的svip10。用了有半年, 最近刚出现的这个问题。 不过我后来找到原因解决了

因为跑的流量太多？

**Comment by Ted-bug** [comment]
开个vip
