### ISSUE TITLE
离线下载还可以用吗？

### ISSUE THREAD

**Issue by luoying-zero** [qjfoidnh/BaiduPCS-Go#341]
在Termux里面编译的v3.9.5版本，显示`添加离线下载任务: 遇到错误, 远端服务器返回错误, 代码: 36001`，明明下载链接在百度app试过可以的

**Comment by luoyingying123** [comment]
链接在百度app试过可以的

**Comment by ltBai** [comment]
> 在Termux里面编译的v3.9.5版本，显示`添加离线下载任务: 遇到错误, 远端服务器返回错误, 代码: 36001`，明明下载链接在百度app试过可以的

您好，请问您解决了吗。我这边磁力链接也添加不到

**Comment by luoying-zero** [comment]
> > 在Termux里面编译的v3.9.5版本，显示`添加离线下载任务: 遇到错误, 远端服务器返回错误, 代码: 36001`，明明下载链接在百度app试过可以的
> 
> 您好，请问您解决了吗。我这边磁力链接也添加不到

还没，我也是添加磁力链的

**Comment by ltBai** [comment]
> > > 在Termux里面编译的v3.9.5版本，显示`添加离线下载任务: 遇到错误, 远端服务器返回错误, 代码: 36001`，明明下载链接在百度app试过可以的
> > 
> > 
> > 您好，请问您解决了吗。我这边磁力链接也添加不到
> 
> 还没，我也是添加磁力链的

哥，这个功能是坏了吗，他那个
# 将百度和腾讯主页, 离线下载到根目录 /
BaiduPCS-Go offlinedl add -path=/ http://baidu.com http://qq.com
这个我看是可用的，这两个原理不一样吗，您有什么解决方式吗，多谢回复

**Comment by luoying-zero** [comment]
> 哥，这个功能是坏了吗，他那个
> # 将百度和腾讯主页, 离线下载到根目录 /
> 
> BaiduPCS-Go offlinedl add -path=/ http://baidu.com http://qq.com 这个我看是可用的，这两个原理不一样吗，您有什么解决方式吗，多谢回复

我也不清楚
![2Q==](https://github.com/user-attachments/assets/c6b877f0-1a97-49aa-8d75-f323797b2bc0)

**Comment by qjfoidnh** [comment]
离线下载功能正常
安卓平台在兼容性上可能有问题，不做支持
