### ISSUE TITLE
3.7.4版本登录账号有缺陷

### ISSUE THREAD

**Issue by mrdobejelly** [qjfoidnh/BaiduPCS-Go#35]
1.有几率出现“缺少stoken，将无法使用转存功能”这句话。
2.但更重要的是根本无法登录，提示“网络错误，http: no Host in request URL”诸如此类的。

对第2点更多说明：
1.退出所有账号重新登录，3.7.2 和3.7.3都能正常登录，3.7.4提示网络错误。
2.用之前版本已经登录了，3.7.4能正常使用，但退出登录后重新登录依旧提示网络错误。

**Comment by qjfoidnh** [comment]
请问登录错误是用bduss登录还是用户名密码登陆时出现的？

**Comment by mrdobejelly** [comment]
bduss + stoken

**Comment by qjfoidnh** [comment]
在Windows 和LInux 64位上均未能复现登录问题，可以蹲一下有没有其他人复现。

**Comment by daiaji** [comment]
@qjfoidnh 复现了一部分……
删除`%APPDATA%\BaiduPCS-Go`目录后用bduss + stoken登陆，如果不重启BaiduPCS-Go，则`ls`时会
`获取目录下的文件列表: 网络错误, Get "https:///rest/2.0/pcs/file?app_id=266719&by=name&limit=0-2147483647&method=list&order=asc&path=%2F": http: no Host in request URL`
重启BaiduPCS-Go后则没有问题……

**Comment by qjfoidnh** [comment]
OK，已经知道问题出在哪儿了

**Comment by daiaji** [comment]
> OK，已经知道问题出在哪儿了

这是host忘记打了？

**Comment by qjfoidnh** [comment]
> > OK，已经知道问题出在哪儿了
> 
> 这是host忘记打了？

增加那个换pcs服务器功能搞出来的事儿，在某些情况下程序会读不到还未初始化的config里的配置，就把空值传过去了。以前直接是const变量，所以没这个问题。
