### ISSUE TITLE
今天开始，没法下载了。获取下载链接失败, 获取下载链接: 遇到错误, 远端服务器返回错误, 代码: 31023, 消息: param error , invalid host

### ISSUE THREAD

**Issue by lloyd18** [qjfoidnh/BaiduPCS-Go#358]
获取下载链接失败, 获取下载链接: 遇到错误, 远端服务器返回错误, 代码: 31023, 消息: param error , invalid host

有相同问题的吗？

**Comment by lloyd18** [comment]
找到原因了，
pcs_addr 只能是 pcs.baidu.com
改成以下这些都会失败
c.pcs.baidu.com
c2.pcs.baidu.com
c3.pcs.baidu.com
c4.pcs.baidu.com
c5.pcs.baidu.com
d.pcs.baidu.com

**Comment by KNaiFen** [comment]
非常有用

**Comment by locyi** [comment]
多谢
