### ISSUE TITLE
转存秒传失败

### ISSUE THREAD

**Issue by daiaji** [qjfoidnh/BaiduPCS-Go#37]
```
transfer 25B2894C131B7A6C439EBDBA22D0B20A#DEA26EDF935C3CA2510509C46B6FEF09#401115555#RJ219097.7z
秒传文件失败, 消息: 秒传文件: 遇到错误, 远端服务器返回错误, 代码: 31062, 消息: file name is inval
```

**Comment by qjfoidnh** [comment]
本地测试这条命令可以正常转存，建议检查输入时是否在末尾混入了某些非法字符或者多打了井号，如果没有可以测试在网盘其他目录下是否可以正常转存。

**Comment by daiaji** [comment]
> 本地测试这条命令可以正常转存，建议检查输入时是否在末尾混入了某些非法字符或者多打了井号，如果没有可以测试在网盘其他目录下是否可以正常转存。

这个命令是完全复制过来的……
Linux上可以正常转存，但Win10死活不行……
有日志可看吗？

**Comment by qjfoidnh** [comment]
已成功复现并解决，下个版本修复
