### ISSUE TITLE
有没有思路，支持下群组功能，比如群组文件转存  大家有思路吗？

### ISSUE THREAD

**Issue by 24** [qjfoidnh/BaiduPCS-Go#39]
群组文件转存  大家有思路吗？

**Comment by qjfoidnh** [comment]
初步分析了一下，工作量应该会挺大，如果后续反馈需求的人多会考虑做一下

**Comment by nvv5** [comment]
隐私空间目录能否加上呢？我分析了一下应该只是多了一步输入二级密码的操作，多了一个_pcs_.safebox的目录，需要用一个SBOXTKN的cookie，列目录用的api/list没有问题。因为golang不太懂，不知道怎么改。如果需要接口信息可以交流一下。留个联系方式。

**Comment by 24** [comment]
说下 分享-->群组 保存文件的难点吧

1. 文件夹大小 以及 文件夹下文件数量 的不确定性

2. 自身空间的容量 以及 群分享的 目录的大小 差异

3. 如果递归保存文件夹中途失败，如何识别出来，并重新保存

都是体力活，麻烦呢。。。
 
也就是说：
保存单个文件容易，递归保存文件夹太麻烦

接口层次上来说：
1. 获取群组列表
2. 获取群组文件夹列表，
3. 获取群组文件夹里面文件的列表，包括翻页数据
4. 保存文件/文件夹的接口

四个接口，不太麻烦。


总结下：
 接口容易，业务麻烦,  体力活。 关 Issues 了

**Comment by jackeymai** [comment]
群组里面的分享文件夹 转存功能是否能够开发一下？

**Comment by jackeymai** [comment]
@24

**Comment by ChitaGideon** [comment]
> 说下 分享-->群组 保存文件的难点吧
> 
> 1. 文件夹大小 以及 文件夹下文件数量 的不确定性
> 2. 自身空间的容量 以及 群分享的 目录的大小 差异
> 3. 如果递归保存文件夹中途失败，如何识别出来，并重新保存
> 
> 都是体力活，麻烦呢。。。
> 
> 也就是说： 保存单个文件容易，递归保存文件夹太麻烦
> 
> 接口层次上来说：
> 
> 1. 获取群组列表
> 2. 获取群组文件夹列表，
> 3. 获取群组文件夹里面文件的列表，包括翻页数据
> 4. 保存文件/文件夹的接口
> 
> 四个接口，不太麻烦。
> 
> 总结下： 接口容易，业务麻烦, 体力活。 关 Issues 了

@24  

接口容易的话能不能实现下基本接口，业务逻辑可以用户自己写

#275
