### ISSUE TITLE
請問也沒有辦法在config裏面提供一個 關閉md5校驗 選項

### ISSUE THREAD

**Issue by ciskonc** [qjfoidnh/BaiduPCS-Go#4]
我發現我經常遇到 md5校驗失敗的情況，然後反覆重下同一個文件。 我知道有--nocheck 的參數 ，但是也沒有可能提供一個開關提供一勞永逸的方法。

**Comment by qjfoidnh** [comment]
dev分支已提交，默认关闭md5校验，可在config中开启（config set -no_check=false）
下个版本号将正式集成
