### ISSUE TITLE
linux amd64上 下载文件失败

### ISSUE THREAD

**Issue by hanksuper** [qjfoidnh/BaiduPCS-Go#41]
错误情况：  

> 
[153] 下载文件失败, Get "https://nb.cache.baidupcs.com/file/*****删掉链接具体信息*****: x509: certificate is valid for baidu.com, baifubao.com, www.baidu.cn, www.baidu.com.cn, mct.y.nuomi.com, apollo.auto, dwz.cn, *.baidu.com, *.baifubao.com, *.baidustatic.com, *.bdstatic.com, *.bdimg.com, *.hao123.com, *.nuomi.com, *.chuanke.com, *.trustgo.com, *.bce.baidu.com, *.eyun.baidu.com, *.map.baidu.com, *.mbd.baidu.com, *.fanyi.baidu.com, *.baidubce.com, *.mipcdn.com, *.news.baidu.com, *.baidupcs.com, *.aipage.com, *.aipage.cn, *.bcehost.com, *.safe.baidu.com, *.im.baidu.com, *.baiducontent.com, *.dlnel.com, *.dlnel.org, *.dueros.baidu.com, *.su.baidu.com, *.91.com, *.hao123.baidu.com, *.apollo.auto, *.xueshu.baidu.com, *.bj.baidubce.com, *.gz.baidubce.com, *.smartapps.cn, *.bdtjrcv.com, *.hao222.com, *.haokan.com, *.pae.baidu.com, *.vd.bdstatic.com, click.hm.baidu.com, log.hm.baidu.com, cm.pos.baidu.com, wn.pos.baidu.com, update.pan.baidu.com, not nb.cache.baidupcs.com

将上面具体的下载链接 在浏览器打开后， 会自动跳转到http://www.baidupcs.com/403.html    显示 ： { "error_code":31326, "error_msg":"anti hotlinking" }

但是通过百度官方客户端下载该文件可以正常下载，而且重复确认，错误 可以重复出现。
能给点解决问题的思路吗？ 谢谢

**Comment by qjfoidnh** [comment]
还真没碰见过，看起来像证书错误。
可以检查一下：
1. 运行时终端是否处于某种代理状态下，或者系统的hosts，路由器里有没有加过什么可疑的东西。
2. 系统时间是否正确
3. 其他文件能否正常下载
4. locate命令获取到的直链是否是nb.cache这个
5. 是否已更新至最新版

**Comment by hanksuper** [comment]
> 还真没碰见过，看起来像证书错误。
> 可以检查一下：
> 
> 1. 运行时终端是否处于某种代理状态下，或者系统的hosts，路由器里有没有加过什么可疑的东西。
> 2. 系统时间是否正确
> 3. 其他文件能否正常下载
> 4. locate命令获取到的直链是否是nb.cache这个
locate 出来有四个结果，手动测试了只有第一个有问题，其它都可以下载下来：
0  https://nb.cache.baidupcs.com/file/23864a03bm05bab1753203bbac6e125d?bkt=en-2d9e6f81f9f5bca0e2776589ed66fa36abe6545519f0ec46a321842abbe75d8a87adb7aaea4e0856df5af1bd723c1bfa396ec0da2d09c58c176ba682f962339c&xcode=f1cc4fc34f9f078698aa9ed955b7f004dba5f9c6936b7bae3f137908723987a059feadfe8c77f9c45ee42e4bbbbb44ca316128a2cdfcce4d&fid=3204948879-250528-329489425826224&time=1613867206&sign=FDTAXUGERQlBHSKfqi-DCb740ccc5511e5e8fedcff06b081203-LeFBVr5705FwdI49aWjXImXyFM0%3D&to=h1&size=974737&sta_dx=974737&sta_cs=108&sta_ft=epub&sta_ct=1&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Cbeijing%2Cct&ctime=1613728046&mtime=1613826163&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=974737&vuk=3204948879&iv=2&htype=&randtype=&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-f62312e1e5e465399cac87024341c4b91c3966adf5753e554e1500a38e117a3750bf62ff6e79c382a741c937383bc3dd639f24d89574b715305a5e1275657320&expires=8h&rt=pr&r=879304651&mlogid=1190996115678307568&vbdid=-&fin=2020-08%E3%80%8A%E6%B2%BB%E6%9C%AF%EF%BC%9A%E5%91%A8%E7%A7%A6%E6%B1%89%E5%94%90%E7%9A%84%E7%BB%8F%E4%B8%96%E4%B9%8B%E9%81%93%E3%80%8B.epub&bflag=h1,44,13,19-h1&check_blue=1&rtype=1&devuid=20A1CC414A6BDF18F71CF7BCE1D5DD27%7C0&clienttype=17&channel=0&dp-logid=1190996115678307568&dp-callid=0.1.1&tsl=0&csl=0&fsl=-1&csign=n083e%2FZ7Xh5nqR1NlCFoTMF2uEg%3D&so=1&ut=1&uter=1&serv=0&uc=566704430&ti=5eee304bbb22b9c291ebe23ae59f88d552a0c9bc61f62f6954086130d5ff933c&hflag=20&from_type=3&adg=c_20a1cc414a6bdf18f71cf7bce1d5dd27&reqlabel=250528_l_339214d12d95e60d4e0f42d6c86435dd_-1_d44323d6282bd28fb7dfc76cba2626c4&ibp=1&by=themis
  1  https://yqct02.baidupcs.com/file/23864a03bm05bab1753203bbac6e125d?bkt=en-2d9e6f81f9f5bca0e2776589ed66fa36abe6545519f0ec46a321842abbe75d8a87adb7aaea4e0856df5af1bd723c1bfa396ec0da2d09c58c176ba682f962339c&fid=3204948879-250528-329489425826224&time=1613867206&sign=FDTAXUGERQlBHSKfWqi-DCb740ccc5511e5e8fedcff06b081203-%2BxqC%2BhD6euzuSsJ2P4MOWyk1j7A%3D&to=44&size=974737&sta_dx=974737&sta_cs=108&sta_ft=epub&sta_ct=1&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Cbeijing%2Cct&ctime=1613728046&mtime=1613826163&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=974737&vuk=3204948879&iv=2&htype=&randtype=&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-f62312e1e5e465399cac87024341c4b91c3966adf5753e554e1500a38e117a3750bf62ff6e79c382a741c937383bc3dd639f24d89574b715305a5e1275657320&expires=8h&rt=pr&r=993578758&mlogid=1190996115678307568&vbdid=-&fin=2020-08%E3%80%8A%E6%B2%BB%E6%9C%AF%EF%BC%9A%E5%91%A8%E7%A7%A6%E6%B1%89%E5%94%90%E7%9A%84%E7%BB%8F%E4%B8%96%E4%B9%8B%E9%81%93%E3%80%8B.epub&bflag=h1,44,13,19-44&check_blue=1&rtype=1&devuid=20A1CC414A6BDF18F71CF7BCE1D5DD27%7C0&clienttype=17&channel=0&dp-logid=1190996115678307568&dp-callid=0.1.1&tsl=0&csl=0&fsl=-1&csign=n083e%2FZ7Xh5nqR1NlCFoTMF2uEg%3D&so=1&ut=1&uter=1&serv=0&uc=566704430&ti=5eee304bbb22b9c291ebe23ae59f88d552a0c9bc61f62f6954086130d5ff933c&hflag=30&from_type=3&adg=c_20a1cc414a6bdf18f71cf7bce1d5dd27&reqlabel=250528_l_339214d12d95e60d4e0f42d6c86435dd_-1_d44323d6282bd28fb7dfc76cba2626c4&ibp=1&by=themis
  2  https://yqall01.baidupcs.com/file/23864a03bm05bab1753203bbac6e125d?bkt=en-2d9e6f81f9f5bca0e2776589ed66fa36abe6545519f0ec46a321842abbe75d8a87adb7aaea4e0856df5af1bd723c1bfa396ec0da2d09c58c176ba682f962339c&fid=3204948879-250528-329489425826224&time=1613867206&sign=FDTAXUGERQlBHSKfWqi-DCb740ccc5511e5e8fedcff06b081203-%2FkgynGhaCkMT%2BsYuEkk5h50qduA%3D&to=13&size=974737&sta_dx=974737&sta_cs=108&sta_ft=epub&sta_ct=1&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Cbeijing%2Cct&ctime=1613728046&mtime=1613826163&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=974737&vuk=3204948879&iv=2&htype=&randtype=&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-f62312e1e5e465399cac87024341c4b91c3966adf5753e554e1500a38e117a3750bf62ff6e79c382a741c937383bc3dd639f24d89574b715305a5e1275657320&expires=8h&rt=pr&r=545576654&mlogid=1190996115678307568&vbdid=-&fin=2020-08%E3%80%8A%E6%B2%BB%E6%9C%AF%EF%BC%9A%E5%91%A8%E7%A7%A6%E6%B1%89%E5%94%90%E7%9A%84%E7%BB%8F%E4%B8%96%E4%B9%8B%E9%81%93%E3%80%8B.epub&bflag=h1,44,13,19-13&check_blue=1&rtype=1&devuid=20A1CC414A6BDF18F71CF7BCE1D5DD27%7C0&clienttype=17&channel=0&dp-logid=1190996115678307568&dp-callid=0.1.1&tsl=0&csl=0&fsl=-1&csign=n083e%2FZ7Xh5nqR1NlCFoTMF2uEg%3D&so=1&ut=1&uter=1&serv=0&uc=566704430&ti=5eee304bbb22b9c291ebe23ae59f88d552a0c9bc61f62f6954086130d5ff933c&hflag=30&from_type=3&adg=c_20a1cc414a6bdf18f71cf7bce1d5dd27&reqlabel=250528_l_339214d12d95e60d4e0f42d6c86435dd_-1_d44323d6282bd28fb7dfc76cba2626c4&ibp=1&by=themis
  3  https://allall02.baidupcs.com/file/23864a03bm05bab1753203bbac6e125d?bkt=en-2d9e6f81f9f5bca0e2776589ed66fa36abe6545519f0ec46a321842abbe75d8a87adb7aaea4e0856df5af1bd723c1bfa396ec0da2d09c58c176ba682f962339c&fid=3204948879-250528-329489425826224&time=1613867206&sign=FDTAXUGERQlBHSKfWqi-DCb740ccc5511e5e8fedcff06b081203-xXsdQNSRPnHWcowYBtqgW8ZwMjE%3D&to=19&size=974737&sta_dx=974737&sta_cs=108&sta_ft=epub&sta_ct=1&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Cbeijing%2Cct&ctime=1613728046&mtime=1613826163&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=974737&vuk=3204948879&iv=2&htype=&randtype=&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-f62312e1e5e465399cac87024341c4b91c3966adf5753e554e1500a38e117a3750bf62ff6e79c382a741c937383bc3dd639f24d89574b715305a5e1275657320&expires=8h&rt=pr&r=776479422&mlogid=1190996115678307568&vbdid=-&fin=2020-08%E3%80%8A%E6%B2%BB%E6%9C%AF%EF%BC%9A%E5%91%A8%E7%A7%A6%E6%B1%89%E5%94%90%E7%9A%84%E7%BB%8F%E4%B8%96%E4%B9%8B%E9%81%93%E3%80%8B.epub&bflag=h1,44,13,19-19&check_blue=1&rtype=1&devuid=20A1CC414A6BDF18F71CF7BCE1D5DD27%7C0&clienttype=17&channel=0&dp-logid=1190996115678307568&dp-callid=0.1.1&tsl=0&csl=0&fsl=-1&csign=n083e%2FZ7Xh5nqR1NlCFoTMF2uEg%3D&so=1&ut=1&uter=1&serv=0&uc=566704430&ti=5eee304bbb22b9c291ebe23ae59f88d552a0c9bc61f62f6954086130d5ff933c&hflag=30&from_type=3&adg=c_20a1cc414a6bdf18f71cf7bce1d5dd27&reqlabel=250528_l_339214d12d95e60d4e0f42d6c86435dd_-1_d44323d6282bd28fb7dfc76cba2626c4&ibp=1&by=themis

> 5. 是否已更新至最新版
用最新的main分支编译出来的

**Comment by qjfoidnh** [comment]
https://wwe.lanzous.com/iY6b3lxox2d

这个你用着看看有没有问题，没有的话下个版本我就修复了。

**Comment by hanksuper** [comment]
> https://wwe.lanzous.com/iY6b3lxox2d
> 
> 这个你用着看看有没有问题，没有的话下个版本我就修复了。

刚测试了，没有问题，可以正常使用
