### ISSUE TITLE
路径问题的困惑

### ISSUE THREAD

**Issue by hanksuper** [qjfoidnh/BaiduPCS-Go#42]
问题来源: 由于要下载的目录里面文件很多，而且经常局部目录会有新文件增加更新（假设不会文件修改，只会增加新文件），比如网盘目录

> 

/
  下载内容顶级目录/
                              二级目录A/ 
                              二级目录B/
                              二级目录C/

下载内容顶级目录太大，所以希望能够分多次下载，但是比如一旦download  二级目录A  的时候，下载会自动放在本地的save_dir/二级目录A下面，而不是 放在本地的save_dir/下载内容顶级目录/二级目录A/，因此希望能做个本地目录和网盘路径的映射一样，这样便于将大的下载任务分解开，或者也便于从网盘下载局部某个目录的更新。

我记得以前的落实是类似映射的模式，比较方便，现在变成了下载网盘无论哪一级的目录会自动放到本地save_dir目录下，会很不方便。 
不知道我这种问题应该怎么方式解决呢？ 谢谢哈

**Comment by qjfoidnh** [comment]
咳咳，这个好像还真是我改的，当初就为了把目录结构打散才接触的这个项目，没想到又回到了原点......

下个版本给download命令加个可选参数吧

**Comment by hanksuper** [comment]
> 咳咳，这个好像还真是我改的，当初就为了把目录结构打散才接触的这个项目，没想到又回到了原点......
> 
> 下个版本给download命令加个可选参数吧

哈哈，好的，多谢

能问下打散的考虑是什么吗？

**Comment by qjfoidnh** [comment]
嘿嘿，当时需要用到的场景打散比较方便

**Comment by burugo** [comment]
请问这个参数增加了吗？ @qjfoidnh 现在全部下载到根目录下，多文件下载很不方便

**Comment by qjfoidnh** [comment]
fullpath参数，详情参见download --help
