### ISSUE TITLE
默认模式下载失败

### ISSUE THREAD

**Issue by chiakge** [qjfoidnh/BaiduPCS-Go#43]
默认模式下载失败，steam以及pcs下载速度慢。

**Comment by qjfoidnh** [comment]
请提供操作系统，软件版本号以及具体的报错信息

**Comment by chiakge** [comment]
Win10 软件3.75
Get 504 报错

**Comment by chiakge** [comment]
Get https://nb.cache.baidupcs.com/file/5770d7522r62abc6453f0878e05437f2?bkt=en-19901565518762c9fe1f7489a750b0a70d1f71416b3b519a32dccac4f2aa846c4b207841dffb2d0f79f2e00d8ef496636d9884cf640fdc4e8064922adac5f790&xcode=7e9780381bc5fc01b5d6e28c7d345a90dbcd2269aad58e6f9456ccc19548e358615eea233eefa7ac5ee81c5b04eab25a316128a2cdfcce4d&fid=1100855640857-250528-358802924101229&time=1613903455&sign=FDTAXUGERQlBHSKfqi-DCb740ccc5511e5e8fedcff06b081203-RXxZFEG7UYpB6ow2GQqC564nKW0%3D&to=h1&size=1019753&sta_dx=1019753&sta_cs=81&sta_ft=jpg&sta_ct=4&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Canhui%2Cct&ctime=1612515551&mtime=1613896694&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1019753&vuk=1100855640857&iv=2&htype=&randtype=&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-451db77c05134049062c983cfcbec6f6bab1fd946103d2f5740e46215844758cd6bd2e3dd5a91e529867ce723d02a92d45c02a3d36a1ca79305a5e1275657320&expires=8h&rt=pr&r=653537398&mlogid=1200726487049907461&vbdid=-&fin=0602%E6%94%B9%E5%8F%A5%E5%AD%90%E4%B8%BB%E8%B0%93%E5%AE%BE%E5%AE%9A%E7%8A%B6%E8%A1%A5.jpg&bflag=h1,44,13,19-h1&check_blue=1&rtype=1&devuid=D977B683D997D5F9634DDD88403644A2%7C0&clienttype=17&channel=0&dp-logid=1200726487049907461&dp-callid=0.1.1&tsl=0&csl=0&fsl=-1&csign=t3gMEZvZRZnInkXDRdZxUllHjlw%3D&so=1&ut=1&uter=1&serv=0&uc=566704430&ti=5f2aaa70d2fd14dee0d4dfb4bc06756557f4a34c19a531f9&hflag=20&from_type=3&adg=c_d977b683d997d5f9634ddd88403644a2&reqlabel=250528_l_092f2bb3ed66419d0b1d5855855dbff6_-1_2cb8e09f9745b7526c0088b305bff890&ibp=1&by=themis: x509: certificate is valid for baidu.com, baifubao.com, www.baidu.cn, www.baidu.com.cn, mct.y.nuomi.com, apollo.auto, dwz.cn, *.baidu.com, *.baifubao.com, *.baidustatic.com, *.bdstatic.com, *.bdimg.com, *.hao123.com, *.nuomi.com, *.chuanke.com, *.trustgo.com, *.bce.baidu.com, *.eyun.baidu.com, *.map.baidu.com, *.mbd.baidu.com, *.fanyi.baidu.com, *.baidubce.com, *.mipcdn.com, *.news.baidu.com, *.baidupcs.com, *.aipage.com, *.aipage.cn, *.bcehost.com, *.safe.baidu.com, *.im.baidu.com, *.baiducontent.com, *.dlnel.com, *.dlnel.org, *.dueros.baidu.com, *.su.baidu.com, *.91.com, *.hao123.baidu.com, *.apollo.auto, *.xueshu.baidu.com, *.bj.baidubce.com, *.gz.baidubce.com, *.smartapps.cn, *.bdtjrcv.com, *.hao222.com, *.haokan.com, *.pae.baidu.com, *.vd.bdstatic.com, click.hm.baidu.com, log.hm.baidu.com, cm.pos.baidu.com, wn.pos.baidu.com, update.pan.baidu.com, not nb.cache.baidupcs.com, 重试 3/3

**Comment by qjfoidnh** [comment]
#41 将在3.7.6版本修复

具体原因是百度pcs新增了一个三级域名节点，但泛域名证书只保护到了二级，使用到该节点下载时即会有证书校验错误。

目测不久后官方会修复，但也不排除其他可能。保险起见建议这两天暂时用官方客户端下载，着急的可以用#41 里的版本（目前只有LInux）。
