### ISSUE TITLE
ubuntu 16.04 无法登陆

### ISSUE THREAD

**Issue by ElonKou** [qjfoidnh/BaiduPCS-Go#45]
Ubuntu登陆的时候，输入手机号码之后需要重新再输入两次验证码，以及再次输入手机验证，输入之后出现
“检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试”
，麻烦问一下，是什么原因，怎么解决，非常感谢？

**Comment by qjfoidnh** [comment]
Ubuntu系统，在本地未能复现

请确保使用的是最新版本，如重试后问题依旧可考虑使用bduss方式登录

**Comment by ElonKou** [comment]
感谢解答，账号密码方式登陆仍然不能成功，但是bduss可以登陆，非常感谢！
