### ISSUE TITLE
能否直接下载至设置中 savedir 的位置

### ISSUE THREAD

**Issue by glatavento** [qjfoidnh/BaiduPCS-Go#47]
在 xxxxxxx 账号中下载 `dl.7z` 文件，若设定 `savedir` 为 `D:\Downloads`，则最终保存位置为 `D:\Downloads\2866613459_xxxxxxx\dl.7z`，其中新建了一个与账号相关的文件夹。能否在设置选项中加入一项开关，使得文件能够直接下载到 `savedir` 中（例如，`D:\Downloads\dl.7z`）？

**Comment by qjfoidnh** [comment]
因为软件是多用户的，而且config里的路径不好判断是用户设置还是默认值，所以建议通过在每次下载时指定--saveto参数来实现需求。
