### ISSUE TITLE
pcs下的transfer.go 转存分享链接 提示 分享链接转存到网盘失败: 请确认登录参数中已经包含了网盘STOKEN

### ISSUE THREAD

**Issue by hanhanwink** [qjfoidnh/BaiduPCS-Go#49]
baidupcs/transfer.go AccessSharePage 140行

`re, _ := regexp.Compile(`yunData\.setData\((\{"loginstate.+?\})\);`)
		sub := re.FindSubmatch(body)
		if len(sub) < 2 {
			tokens["ErrMsg"] = "请确认登录参数中已经包含了网盘STOKEN"
			return
		}`

debug发现 页面里没有yunData.setData 而是 locals.mset

**Comment by hanhanwink** [comment]
修改正则匹配json信息出来 还是不正确 是被baidu 关照了吗

**Comment by hanhanwink** [comment]
@qjfoidnh

**Comment by qjfoidnh** [comment]
接口除了这里还有别的地方也变了，3.7.7版已修复

------
转存正常的用户请勿更新

**Comment by hanhanwink** [comment]
好的 已经更新解决
