### ISSUE TITLE
突然登录不了了

### ISSUE THREAD

**Issue by JasonQAQ** [qjfoidnh/BaiduPCS-Go#50]
输入两遍验证码后发送短信，输入短信后继续输入两遍验证码，然后又出现选择验证方式，选择完出现：
请输入验证方式 (1 或 2) > 1
消息: 系统出错: 请稍后重试

检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试

**Comment by qjfoidnh** [comment]
不太好确定什么状况，本地测试登录正常

鉴于用户名密码登录出问题的概率比较大，后续可能停止此登录方式的维护，建议换成BDUSS或Cookies登录
