### ISSUE TITLE
上传 400BadRequest重试机制导致进程访问的fd(TCP)过多 最后导致too many file open

### ISSUE THREAD

**Issue by BanksyPunk** [qjfoidnh/BaiduPCS-Go#51]
上传命令:
```BaiduPCS-Go upload --norapid --retry 100 source dest```
大概十几个任务400失败后(总上传队列有50几个任务),会触发句柄上限,因为机器安装了es,ulimit 已经调高到了65535
```lsof -n|awk '{print $2}'|sort|uniq -c|sort -nr|head -n 10```
``` 
154229 21074
     77 2993
     70 4938
     68 506
     64 531
     64 4056
     60 1237
     52 1851
     44 1896
     40 500
```
查看lsof 每当一个文件上传返回400后 fd数继续增长
上面是10个任务失败 进入重试队列1/100后的数据(pid:21074为BaiduPCS)
```lsof -p 21074 | grep TCP | wc -l```
``` 3413 ```
```lsof -p 21074  | wc -l```
```3667```
请问配置中有没有可以限制上传TCP链接数或者修改重试逻辑的地方

**Comment by qjfoidnh** [comment]
优化了一下tcp复用的部分，本地测试大概能减少一半的连接数，已推送至主仓库
如果还是会超就只能在requester/http_client.go 42行改掉keepalive了，经测试连接数将减少为上传线程数，但频繁建立TCP连接会显著影响上传速度
