### ISSUE TITLE
 获取下载链接失败, 获取下载链接: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:117

### ISSUE THREAD

**Issue by Jio0oiJ** [qjfoidnh/BaiduPCS-Go#53]
获取下载链接失败, 获取下载链接: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:117
各种重新登录，改user-agent都不行

**Comment by qjfoidnh** [comment]
#2 一般来说是非SVIP用户使用了多线程下载导致，可等几天再来使用，并在使用时将max_parallel设为1

**Comment by Jio0oiJ** [comment]
也不完全是，很奇怪，有些文件给下，有些不给下。。

**Comment by e9965** [comment]
> 也不完全是，很奇怪，有些文件给下，有些不给下。。

下载的文件违规，--fix 指令没效，尝试用脚本修复

**Comment by qjfoidnh** [comment]
本软件只支持秒传链接修复，download命令不提供--fix功能

**Comment by xizhukarsa** [comment]
> 本软件只支持秒传链接修复，download命令不提供--fix功能

所以，这个这个问题有推荐的方案么？

**Comment by xizhukarsa** [comment]
> > 本软件只支持秒传链接修复，download命令不提供--fix功能
> 
> 所以，这个这个问题有推荐的方案么？

好吧，还是金钱的味道好闻，开通超级vip就丝般顺滑了 ~
