### ISSUE TITLE
更新程序时下载地址是否可以使用fastgit地址?

### ISSUE THREAD

**Issue by hfpiao** [qjfoidnh/BaiduPCS-Go#54]
https://github.com/qjfoidnh/BaiduPCS-Go/releases/download/v3.7.8/BaiduPCS-Go-v3.7.8-windows-x64.zip

替换成:
https://hub.fastgit.org/qjfoidnh/BaiduPCS-Go/releases/download/v3.7.8/BaiduPCS-Go-v3.7.8-windows-x64.zip

**Comment by qjfoidnh** [comment]
貌似不可，除非找到api.github.com的对应加速

**Comment by hfpiao** [comment]
api.github.com 这个还是用github没问题, 我本地直接文本替换成fastgit(github.com替换为hub.fastgit.org)是可以加速下载的.
![image](https://user-images.githubusercontent.com/4986967/112602531-c3e39f80-8e4e-11eb-84b5-0a7fe8f5b801.png)

**Comment by qjfoidnh** [comment]
那应该可以
