### ISSUE TITLE
关于转存的问题

### ISSUE THREAD

**Issue by JasonQAQ** [qjfoidnh/BaiduPCS-Go#55]
如按以下命令格式可以转存成功：
BaiduPCS-Go transfer https://pan.baidu.com/s/12L_ZZVNxz5f_2CccoyyVrW edv4
但如果链接为变量时无法转存：
如：
url="https://pan.baidu.com/s/12L_ZZVNxz5f_2CccoyyVrW edv4"
BaiduPCS-Go transfer $url
或者：
url="https://pan.baidu.com/s/12L_ZZVNxz5f_2CccoyyVrW"
pw="edv4"
BaiduPCS-Go transfer $url $pw
或者
BaiduPCS-Go transfer "$url $pw"

此时会报错：
分享链接转存到网盘失败: 链接地址或提取码非法

**Comment by qjfoidnh** [comment]
![QQ20210326-215400@2x.png](https://i.loli.net/2021/03/26/RKNDITFsJgm4el2.png)
![QQ20210326-215417@2x.png](https://i.loli.net/2021/03/26/NKaQY8OE2m6AUTM.png)
并未出现问题

**Comment by JasonQAQ** [comment]
找到原因了，是因为我的变量从文本文档中读取的，而格式来源于windows，所以包含了^M导致格式出错，谢谢

**Comment by JasonQAQ** [comment]
> ![QQ20210326-215400@2x.png](https://camo.githubusercontent.com/b3777f4dcdbe99ae8a4fc8720ec8bfb0e6c0d25dab0e42a51f9fefbed8f49fe6/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30332f32362f524b4e44495446734a676d34656c322e706e67)
> ![QQ20210326-215417@2x.png](https://camo.githubusercontent.com/56d264a5ebe02fda2716229735d43981d66b4166358ce0f03d4fece5783e15ff/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30332f32362f4e4b615159384f45326d364155544d2e706e67)
> 并未出现问题

找到原因了，是因为我的变量从文本文档中读取的，而格式来源于windows，所以包含了^M导致格式出错，谢谢
