### ISSUE TITLE
输出运行结果

### ISSUE THREAD

**Issue by hdg8087** [qjfoidnh/BaiduPCS-Go#56]
两个问题求助：

【1】share set /A/a.zip >D:\1.txt
我想把a.zip文件的分享链接结果输出到1.txt文件里，
但运行结果总是：创建分享链接失败: 创建分享链接: 遇到错误, 远端服务器返回错误, 代码: 2, 消息: 参数错误
share set /A/a.zip输出结果却正确。
想输出结果，如何写命令呢？

【2】如果有多个网盘文件想分享，一个文件一个链接，
share set /A/a.zip
share set /A/b.zip
share set /A/c.zip
所有分享链接最后输出到文件1.txt里，如何写呢？

**Comment by qjfoidnh** [comment]
重定向只能在终端环境里用的哈，程序share方法没有这个的。

直接在cmd里：BaiduPCS-Go.exe share set xxxxx >D:\xxx.txt
这样可以
不要点开BaiduPCS-Go再输命令

第二个问题同样是shell语言问题，写个循环可以解决。作者对Windows的命令行不太熟，仅提供思路。

**Comment by hdg8087** [comment]
呃，好吧，这个表述太专业啊，能否通俗一点，告诉我如何能达到上述目的？

**Comment by hdg8087** [comment]
ok，明白了。感谢。

**Comment by hdg8087** [comment]
批量分享链接，假如有2000个文件，直接循环，要不要延时？
我怕太快速的话，容易被百度网盘封。

**Comment by hdg8087** [comment]
当然，我说的是2000个文件逐一分享。

**Comment by qjfoidnh** [comment]
呃...分享不是啥敏感操作，我觉得不会

但保险起见可以间隔个一两秒
