### ISSUE TITLE
分享功能是不是出问题了？

### ISSUE THREAD

**Issue by hdg8087** [qjfoidnh/BaiduPCS-Go#57]
share set /2888/1/d0730.zip
这样的命令，之前都是可以有分享链接出来的
后来就报错了：创建分享链接失败: 创建分享链接: 遇到错误, 远端服务器返回错误, 代码: 2, 消息: 参数错误
我确定：路径没有错、网盘帐号没有错、之前类似的路径也可以运行成功。

**Comment by hdg8087** [comment]
pcs的其它命令没有问题，比如 tree，就没问题。

**Comment by qjfoidnh** [comment]
本地测试是正常的，提供几个思路排除：
1. 重新使用网页端获取的bduss登录
2. 在网页或官方客户端分享一个文件
3. 如果命令内容是从txt里读取的，可能是Windows里换行符一类的问题，参加#55

**Comment by hdg8087** [comment]
试了，是百度网盘的分享数量限制。
另外，手动分享网盘文件的时候，会有访问人数、有限期的限制。
限制我知道baidupcs是永久，
但访问人数有没有限制啊？

**Comment by qjfoidnh** [comment]
呃，这个就不知道了

**Comment by hdg8087** [comment]
你开发的时候，没有对这个进行设置吗？

**Comment by qjfoidnh** [comment]
没注意，可能是近期新加的。像这种不传值一般会赋一个默认人数，等有空了看看

**Comment by hdg8087** [comment]
![image](https://user-images.githubusercontent.com/71086865/112858132-2b664d00-90e4-11eb-932a-b851039f718f.png)
请问这是怎么回事啊？
网盘帐号没有登错，
网盘里也有很多文件，
但tree命令输进去以后，
下一行没有结果，还是出来baidupcs的提示符。

**Comment by qjfoidnh** [comment]
这……没有抓包信息也不好排查，个人感觉是不触发啥账号保护机制了？

**Comment by hdg8087** [comment]
我重新登录就没事了，不过，我之前登录这个帐号后，没有对这个帐号进行任何操作。然后只在同电脑上登录另一个帐号，分享了一些文件。不知道有没有关系。

**Comment by cbc123** [comment]
> 
你已经确定是百度网盘做了分享次数限制嘛。我删了之前分享的还是不行
