### ISSUE TITLE
上传前检查文件名合法

### ISSUE THREAD

**Issue by AmCh-Q** [qjfoidnh/BaiduPCS-Go#59]
如果文件名里面带一些非法符号的话，上传传输完了(才)会400 Bad Request
估计是百度网盘没法接受这类文件名，还偏偏是数据传输完了才会报这个问题
估计 \ / : * ? " < > | 都有可能不行，我没一个一个试，但是可以确认 > 和 | 会400
参考复现测试：
```echo "abcd" > file\>name.txt```
```BaiduPCS-Go u file\>name.txt /```

**Comment by qjfoidnh** [comment]
下个版本将在上传前增加文件名合法性检查

**2021.4.18更新**
4.18前发布的3.7.9版本在Windows平台有重大上传Bug，之前已更新3.7.9的朋友请重新下载。

**Comment by pongfcnkl** [comment]
@qjfoidnh 
3.7.9 一上传几乎所有文件都是不合法的，得要把/这个符号去掉。

**Comment by pongfcnkl** [comment]
> 
> 
> @qjfoidnh
> 3.7.9 一上传几乎所有文件都是不合法的，得要把/这个符号去掉。建议做成自定义

**Comment by qjfoidnh** [comment]
只对文件名中的'/'进行了检查，路径没有检查'/'，Linux测试上传正常
请问你用的是Windows系统么？

--------

发现了，在上传目录时会误报

**Comment by jyuan15** [comment]
windows 10测试，会把路径中的斜杠 / 识别为非法字符，导致无法上传

**Comment by qjfoidnh** [comment]
现在发布的版本应该是已经修复了的，重新下载一下试试呢

**Comment by jyuan15** [comment]
> 现在发布的版本应该是已经修复了的，重新下载一下试试呢

就是昨天才下载的最新版（3天前发布的），你这么说，我又再次重下来试试，还是不行啊

![2021-04-18_092242](https://user-images.githubusercontent.com/12642186/115131107-f89adf00-a027-11eb-8d69-568b3b7eb3e6.jpg)

**Comment by qjfoidnh** [comment]
> > 现在发布的版本应该是已经修复了的，重新下载一下试试呢
> 
> 就是昨天才下载的最新版（3天前发布的），你这么说，我又再次重下来试试，还是不行啊
> 
> ![2021-04-18_092242](https://user-images.githubusercontent.com/12642186/115131107-f89adf00-a027-11eb-8d69-568b3b7eb3e6.jpg)

...才发现，不是/，是冒号...

**Comment by jyuan15** [comment]
> > > 现在发布的版本应该是已经修复了的，重新下载一下试试呢
> > 
> > 
> > 就是昨天才下载的最新版（3天前发布的），你这么说，我又再次重下来试试，还是不行啊
> > ![2021-04-18_092242](https://user-images.githubusercontent.com/12642186/115131107-f89adf00-a027-11eb-8d69-568b3b7eb3e6.jpg)
> 
> ...才发现，不是/，是冒号...

已经正常了，非常感谢！
