### ISSUE TITLE
公司网络登录失败

### ISSUE THREAD

**Issue by brynne8** [qjfoidnh/BaiduPCS-Go#61]
公司默认是禁止访问百度贴吧的，BaiduPCS-Go似乎是用贴吧来验证bduss是否有效的。能不能改用其他网址？比如百度知道。

**Comment by qjfoidnh** [comment]
这个问题我更建议通过挂代理/VPN解决，理论上国内甚至国际的梯子都可以，只要登录时用一下就OK，以后就不需要了。

如果公司的屏蔽实在强大，甚至可以直接把家里的pcs_config.json复制到公司，等同于登录了。

**Comment by brynne8** [comment]
好吧。不过我觉得改用其他网址是有价值的。感谢提供这个方法。
