### ISSUE TITLE
请问能否跳过秒传检测

### ISSUE THREAD

**Issue by kdurov** [qjfoidnh/BaiduPCS-Go#63]
请问上传时能否跳过秒传检测。
自己制作的文件可以确定不会MD5值相同，也要经过漫长的秒传检测。
请问是否能跳过这浪费时间一步骤？

谢谢

**Comment by qjfoidnh** [comment]
参见upload --help，有 --norapid参数

**Comment by kdurov** [comment]
谢谢。没注意upload参数还有help内容。
