### ISSUE TITLE
文件上传失败

### ISSUE THREAD

**Issue by davidekingsss** [qjfoidnh/BaiduPCS-Go#64]
添加文件上传后，上传进度达到30MB左右就会重新开始下载，同时没有报错，就这样反复横跳，4线程最多4文件的配置下，显示的上传数据的总量大约90~100MB左右，无论单个文件还是多个文件的和基本都在这个范围，离谱的很，windows和linux环境都有这个问题

**Comment by davidekingsss** [comment]
退回到上一版本没有此问题

**Comment by qjfoidnh** [comment]
请问上传时的网速大概为多少呢
或者说上传开始约多少秒后出现异常

**Comment by davidekingsss** [comment]
第一秒开始就这样了，上面的配置是下载到30mb时回退，我试着把线程改到1，就差不多是90多m的时候回退，再多的就没试了
网速也有异常，我另一个电脑正在全速上传，而这边软件的上传速度还能跑满上行速度，甚至还能超，而且有的时候不检查秒传
特别小的文件是可以正常上传的，我试着把软件压缩包上传到百度云，是的的确确上传成功了的
