### ISSUE TITLE
秒传链接转存失败的非常奇怪

### ISSUE THREAD

**Issue by davidekingsss** [qjfoidnh/BaiduPCS-Go#65]
1. 同一个秒传链接，在网页脚本上转存是没问题的，在软件里转存会报错31079
2. 用软件上传的一个文件，秒传链接在网页插件和软件中同时显示失效，删除源文件后重新用软件不分片单线程上传，再次转存，两端仍均失效，用百度云上传，两端上传均正常

软件上会报错但网页端没问题的秒传链接：`D6E7CCFEEC03DEE1CDBE37C5C7CE4427#2D6B0CBF8276F6E0295C287511417056#734003200#20210325010704255301002620210401174840.part1.rar`

**Comment by pongfcnkl** [comment]
不能有大写，要转小写
