### ISSUE TITLE
上传文件失败, 分片上传—文件分片及上传: 网络错误, http 响 应错误, 400 Bad Request, 重试 1/3

### ISSUE THREAD

**Issue by fvlw** [qjfoidnh/BaiduPCS-Go#68]
版本
v3.7.9
上传失败后提示分片上传失败,是按照什么方式处理
1 全部重新上传
2 按照之前的进度续传

文件大小是290.39GB 能分片成功吗
![图片](https://user-images.githubusercontent.com/71577616/118348100-94adfc80-b57a-11eb-827a-d825164d0201.png)

**Comment by qjfoidnh** [comment]
400错误码会全部重新上传，以后的版本可能会测试一下只重传分片是否可行。

理论上分片是可以成功的，但没实际测试过。

**Comment by mrdobejelly** [comment]
啊，原来是可以上传超过20G的文件的吗，我现在才知道，能成功吗200G

**Comment by fvlw** [comment]
> 
> 
> 啊，原来是可以上传超过20G的文件的吗，我现在才知道，能成功吗200G

不行 20G可以 200G不行

**Comment by fvlw** [comment]
v3.8.0 
50G上传失败 
![图片](https://user-images.githubusercontent.com/71577616/120572021-dd582780-c44d-11eb-9584-6b64cb2a3e78.png)

**Comment by fvlw** [comment]
v3.8.0 
50G上传失败 
![图片](https://user-images.githubusercontent.com/71577616/120577576-18128d80-c457-11eb-80a8-992f71929b7a.png)
