### ISSUE TITLE
台灣 IP 轉存失敗

### ISSUE THREAD

**Issue by cges30901** [qjfoidnh/BaiduPCS-Go#70]
台灣 IP 已經被封鎖很久了，目前在不使用 VPN 的前提下轉存的方法大概就是使用手機版網頁了，如果用 BaiduPCS-Go 會出現以下錯誤訊息：
```
分享链接转存到网盘失败: 页面不存在
```
請問有辦法讓 BaiduPCS-Go 在台灣能轉存嗎？

**Comment by qjfoidnh** [comment]
这种封锁没有太好的解决方法，只能想办法通过代理挂到大陆或欧美地区

**Comment by nazhendenb** [comment]
难怪我有时候在电脑上用网页存资源，关了梯子就好了

**Comment by nazhendenb** [comment]
难怪我有时候在电脑上用网页存资源，关了梯子就好了
