### ISSUE TITLE
上传文件时候出现问题

### ISSUE THREAD

**Issue by xxtitan** [qjfoidnh/BaiduPCS-Go#71]
版本v3.7.9
在海外服务器上上传
4线程的时候达到8M/s
但是同样遇到“上传数据的总量大约90~100MB左右” 然后已上传的大小会回跳到100M以内”（似乎是重新上传了）
这个问题和 #64 一样
回滚到v3.7.8没有出现相同情况，正常上传

**Comment by xxtitan** [comment]
可能是
internal/pcsfunctions/pcsupload/upload.go文件中
`client.SetTimeout(0)` 被修改为一个过小的TimeOut的原因？

**Comment by qjfoidnh** [comment]
确实是超时的问题，下个版本将修复。也可以手动编译最新的代码
