### ISSUE TITLE
麻烦添加一个功能   多个 不同 <目标目录>

### ISSUE THREAD

**Issue by vijaykarani333** [qjfoidnh/BaiduPCS-Go#73]
目前我们有 BaiduPCS-Go u <本地文件/目录的路径1> <文件/目录2> <文件/目录3> ... <目标目录>
是否可以添加多个<目标目录> 呢？ 例如
<本地文件/目录的路径1>___ <目标目录0> <目标目录1>
有时候一个指令 备份到多个 不同<目标目录> 也有点价值的. 先感谢了

**Comment by qjfoidnh** [comment]
这个操作不是原子操作，没有必要开发单独功能
建议通过脚本/批处理实现

以Linux为例

#!/bin/bash
BaiduPCS-Go u <本地文件/目录的路径1>
BaiduPCS-Go u <本地文件/目录的路径2>
BaiduPCS-Go u <本地文件/目录的路径3>
......

也可以将u换成cp免去秒传检测
