### ISSUE TITLE
下载并发 max_parallel 的推荐区间是多少

### ISSUE THREAD

**Issue by oshino29** [qjfoidnh/BaiduPCS-Go#74]
想要提高速度但是怕设定太高被限制账号/限制 IP

**Comment by qjfoidnh** [comment]
没有SVIP强烈建议设为1，否则短时间内大概率封号（目前严格来说还没有三方客户端可以真正破解普通用户速度）
SVIP一般设为10左右就可以跑满带宽了，可稳定使用。

**Comment by oshino29** [comment]
> 没有SVIP强烈建议设为1，否则短时间内大概率封号（目前严格来说还没有三方客户端可以真正破解普通用户速度）
> SVIP一般设为10左右就可以跑满带宽了，可稳定使用。

可以提到 10 的哇，前面怕封号战战兢兢只敢设定到 2 乌龟爬，谢谢回复！

**Comment by nazhendenb** [comment]
> 没有SVIP强烈建议设为1，否则短时间内大概率封号（目前严格来说还没有三方客户端可以真正破解普通用户速度）
> SVIP一般设为10左右就可以跑满带宽了，可稳定使用。

问一下下载并发是什么意思？   
假设设置为5， 当我同时下载5个文件时 会开启5个线程同时下载，这个好理解。
那只下载1个文件会怎么样？切片然后同样开启5个线程上传？还是说仍然只有一个线程

**Comment by qjfoidnh** [comment]
> > 没有SVIP强烈建议设为1，否则短时间内大概率封号（目前严格来说还没有三方客户端可以真正破解普通用户速度）
> > SVIP一般设为10左右就可以跑满带宽了，可稳定使用。
> 
> 问一下下载并发是什么意思？
> 假设设置为5， 当我同时下载5个文件时 会开启5个线程同时下载，这个好理解。
> 那只下载1个文件会怎么样？切片然后同样开启5个线程上传？还是说仍然只有一个线程

下载并发数这里认为指max_parallel参数，这个参数不受同时下载文件数影响，原理是对所有文件进行不大于4MB的切片并以max_parallel数量的线程来下载这些切片。

所以不管同时下载几个文件，全局下载线程数都是5，只是文件一多每个文件匀到的线程就少了，但总速度不会变。

**Comment by nazhendenb** [comment]
> > > 没有SVIP强烈建议设为1，否则短时间内大概率封号（目前严格来说还没有三方客户端可以真正破解普通用户速度）
> > > SVIP一般设为10左右就可以跑满带宽了，可稳定使用。
> > 
> > 
> > 问一下下载并发是什么意思？
> > 假设设置为5， 当我同时下载5个文件时 会开启5个线程同时下载，这个好理解。
> > 那只下载1个文件会怎么样？切片然后同样开启5个线程上传？还是说仍然只有一个线程
> 
> 下载并发数这里认为指max_parallel参数，这个参数不受同时下载文件数影响，原理是对所有文件进行不大于4MB的切片并以max_parallel数量的线程来下载这些切片。
> 
> 所以不管同时下载几个文件，全局下载线程数都是5，只是文件一多每个文件匀到的线程就少了，但总速度不会变。

噢  懂了
看来BaiduPCS-Go的并发是真并发，隔壁rclone的并发是假的( )
 
一样的参数名，它的含义是同时上传的文件数量，对应PCSGo的 max_download_load
