### ISSUE TITLE
功能建议：希望添加上传跳过同名文件功能

### ISSUE THREAD

**Issue by zzzop** [qjfoidnh/BaiduPCS-Go#75]
原因是上传20000个小文件（10-600m大小）时，发现其中一个文件存在反复上传，不成功也不失败的状态。同名文件会覆盖的话也不好重新开始任务。
命令 参数是`./BaiduPCS-Go upload --norapid --nosplit -l 4 /mnt/sdb1 .`

**Comment by qjfoidnh** [comment]
反复上传不太清楚是什么状况，上传遇到同名文件默认会直接覆盖

下个版本会增加自动重命名选项

**Comment by zzzop** [comment]
> 反复上传不太清楚是什么状况，上传遇到同名文件默认会直接覆盖
> 
> 下个版本会增加自动重命名选项

不考虑跳过吗，这样也能用来同步文件

**Comment by qjfoidnh** [comment]
暂不考虑

**Comment by zzzop** [comment]
好的

**Comment by qjfoidnh** [comment]
最后还是决定用跳过策略了
