### ISSUE TITLE
office api support

### ISSUE THREAD

**Issue by ericma15** [qjfoidnh/BaiduPCS-Go#77]
Baidu Pan now offer offical api abot it .Can you consider support it?
https://pan.baidu.com/union/document/basic

**Comment by qjfoidnh** [comment]
看了一下，应该是需要使用者申请秘钥，有一定使用门槛

目前应该没什么必要换，但也许是条后路

**Comment by ericma15** [comment]
好的，另外我测试他提供的一部分新api，不用accesstoken而是采用cookie也可以正常访问，这一类也许是比较持久的api了
