### ISSUE TITLE
连接转存失败

### ISSUE THREAD

**Issue by huzhe007** [qjfoidnh/BaiduPCS-Go#8]
错误信息
分享链接转存到网盘失败: 分享页面解析失败

**Comment by qjfoidnh** [comment]
请确保已更新至3.6.2版本，并使用cookies方式登录且cookies字段取自百度网盘首页未删减。
如问题仍存在，可尝试其他分享链接观察问题是否复现。

**Comment by huzhe007** [comment]
> 请确保已更新至3.6.2版本，并使用cookies方式登录且cookies字段取自百度网盘首页未删减。
> 如问题仍存在，可尝试其他分享链接观察问题是否复现。
