### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by xixky** [qjfoidnh/BaiduPCS-Go#82]
[75] 准备下载: /Java尚融宝项目/金融项目--尚融宝/视频/day13/上午/260-尚硅谷-尚融宝-SpringCloud基础设置【瑞客论坛 www.ruike1.com】.mp4
[75] 将会下载到路径: /mnt/bd/xxx/Java尚融宝项目/金融项目--尚融宝/视频/day13/上午/260-尚硅谷-尚融宝-SpringCloud基础设置【瑞客论坛 www.ruike1.com】.mp4

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5daeb1]

goroutine 174 [running]:
net.(*Resolver).tryOneName(0x10a1920, 0xc22fc0, 0xc00026fd00, 0xc0001a2640, 0xc0003231c0, 0x15, 0x1c, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:254 +0x281
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0x10a1920, 0xc22fc0, 0xc00026fd00, 0xc0001a2640, 0xc0003231c0, 0x15, 0xc0002b3860, 0x1c)
        /usr/local/go/src/net/dnsclient_unix.go:602 +0x91
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:601 +0xd8

**Comment by qjfoidnh** [comment]
看上去像dns解析的问题，可以检查下/etc/resolv.conf，其他的我也不太清楚

**Comment by xixka** [comment]
好像是腾讯云轻量自带的dns问题，我再看看

**Comment by hanksuper** [comment]
如何解决呢？ 我也遇到了，可以复现
我是在我群晖的系统上遇到的

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x5d3307]

goroutine 748 [running]:
net.(*Resolver).tryOneName(0xec9660, 0xb6b838, 0xc000c39940, 0xc0002405a0, 0xc000f4d248, 0x14, 0x1c, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:253 +0x287
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xec9660, 0xb6b838, 0xc000c39940, 0xc0002405a0, 0xc000f4d248, 0x14, 0xc000c6db00, 0xa4001c)
	/usr/local/go/src/net/dnsclient_unix.go:601 +0xbb
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
	/usr/local/go/src/net/dnsclient_unix.go:600 +0xd8

**Comment by hanksuper** [comment]
> 好像是腾讯云轻量自带的dns问题，我再看看
最后解决了吗？

**Comment by hanksuper** [comment]
> 好像是腾讯云轻量自带的dns问题，我再看看

最后解决了吗？

**Comment by xixka** [comment]
> > 好像是腾讯云轻量自带的dns问题，我再看看
> 
> 最后解决了吗？

修改腾讯云广州默认的dns就可以了

**Comment by xixka** [comment]
在甲骨文arm又一次触发这个bug了，
通过修改dns为 1.1.1.1 然后使用 sudo systemd-resolve --statistics 清空dns缓存 解决这个问题
