### ISSUE TITLE
出大事了，原来没有同名文件提示！

### ISSUE THREAD

**Issue by mrdobejelly** [qjfoidnh/BaiduPCS-Go#83]
上传的时候忘记改文件名，结果把原来的同名文件给覆盖了！40G的文件骤然消失，我太难了。
这个功能如果可以实现请务必增加。覆盖掉的文件也不是被删除了因为回收站里也没有，凭空消失无法找回啊！

**Comment by qjfoidnh** [comment]
心疼一波老哥......如果以前记录过文件的秒传信息可以通过秒传找回来，如果莫得。。。大概真就没了

软件的默认策略确实是覆盖，在实现逻辑上是通过百度网盘官方API的参数控制的，做出提示比较困难，但3.8.1可以通过--skip来修改重名策略为自动跳过，下个版本可能会增加自动重命名的策略选项。
