### ISSUE TITLE
欠缺安装的说明

### ISSUE THREAD

**Issue by Ethan-LWT** [qjfoidnh/BaiduPCS-Go#84]
系统是Mac，在terminal下git clone后，cd进入了该文件夹后就不知道怎么操作了，尝试了直接敲命令BaiduPCS-Go却没有反应。
麻烦能不能不要把某些重要的步骤省略掉。希望尽快跟进。谢谢

**Comment by qjfoidnh** [comment]
这个是本地编译的步骤，非开发者是不需要的。

直接在蓝奏云或者release下载已编译的二进制程序，单文件没有安装的说法。运行方式与Linux中可执行程序一样
