### ISSUE TITLE
下载文件的路径能不能用变量？

### ISSUE THREAD

**Issue by daiaji** [qjfoidnh/BaiduPCS-Go#88]
RT

**Comment by qjfoidnh** [comment]
可以。虽然交互式界面不支持变量，但是命令行式是可以使用Linux的变量的，比如--saveto $LOCAL_PATH 这种

**Comment by daiaji** [comment]
> 可以。虽然交互式界面不支持变量，但是命令行式是可以使用Linux的变量的，比如--saveto $LOCAL_PATH 这种

WIN呢？

**Comment by qjfoidnh** [comment]
win也可以的，比如在powershell里：
$llss="ls"
./BaiduPCS-Go.exe $llss

**Comment by daiaji** [comment]
@qjfoidnh 我想了想，便携用途的时候整不了，毕竟也不想下到U盘里，电脑的盘符也未必一样，如果要把文件存到 `D:%HOMEPATH%\Downloads`果然还是要读取环境变量。
