### ISSUE TITLE
用分享链接转存到网盘失败: 缺少提取码

### ISSUE THREAD

**Issue by JasonQAQ** [qjfoidnh/BaiduPCS-Go#9]
用cookies的方法登录了还是出现如下报错

用分享链接转存到网盘失败: 缺少提取码

会不会是由于现在网盘链接转存也需要验证码的原因？

**Comment by qjfoidnh** [comment]
请确保已更新至3.6.2版本，并使用百度网盘页面的完整cookies登入。

如仍未解决，能否发一下出现问题时的输入，我看看是否可以复现。

**Comment by JasonQAQ** [comment]
> 请确保已更新至3.6.2版本，并使用百度网盘页面的完整cookies登入。
> 
> 如仍未解决，能否发一下出现问题时的输入，我看看是否可以复现。

不好意思，确实是下错了版本，解决了，谢谢！
但是还有一个问题是不支持http链接，http链接会提示分享链接转存到网盘失败: 链接地址或提取码非法

**Comment by qjfoidnh** [comment]
> > 请确保已更新至3.6.2版本，并使用百度网盘页面的完整cookies登入。
> > 如仍未解决，能否发一下出现问题时的输入，我看看是否可以复现。
> 
> 不好意思，确实是下错了版本，解决了，谢谢！
> 但是还有一个问题是不支持http链接，http链接会提示分享链接转存到网盘失败: 链接地址或提取码非法

http是支持的，且地址带不带协议头均可，可以检查是否有少打'/'等问题；如果是过去那种短链接的分享地址是不支持的。

**Comment by JasonQAQ** [comment]
> > > 请确保已更新至3.6.2版本，并使用百度网盘页面的完整cookies登入。
> > > 如仍未解决，能否发一下出现问题时的输入，我看看是否可以复现。
> > 
> > 
> > 不好意思，确实是下错了版本，解决了，谢谢！
> > 但是还有一个问题是不支持http链接，http链接会提示分享链接转存到网盘失败: 链接地址或提取码非法
> 
> http是支持的，且地址带不带协议头均可，可以检查是否有少打'/'等问题；如果是过去那种短链接的分享地址是不支持的。

对，就是那种短链接要如何处理呢？

**Comment by JasonQAQ** [comment]
> > > 请确保已更新至3.6.2版本，并使用百度网盘页面的完整cookies登入。
> > > 如仍未解决，能否发一下出现问题时的输入，我看看是否可以复现。
> > 
> > 
> > 不好意思，确实是下错了版本，解决了，谢谢！
> > 但是还有一个问题是不支持http链接，http链接会提示分享链接转存到网盘失败: 链接地址或提取码非法
> 
> http是支持的，且地址带不带协议头均可，可以检查是否有少打'/'等问题；如果是过去那种短链接的分享地址是不支持的。

用另一个工具包解决了，谢谢，https://github.com/hxz393/BaiduPanFilesTransfers/issues/10

**Comment by qjfoidnh** [comment]
> > > > 请确保已更新至3.6.2版本，并使用百度网盘页面的完整cookies登入。
> > > > 如仍未解决，能否发一下出现问题时的输入，我看看是否可以复现。
> > > 
> > > 
> > > 不好意思，确实是下错了版本，解决了，谢谢！
> > > 但是还有一个问题是不支持http链接，http链接会提示分享链接转存到网盘失败: 链接地址或提取码非法
> > 
> > 
> > http是支持的，且地址带不带协议头均可，可以检查是否有少打'/'等问题；如果是过去那种短链接的分享地址是不支持的。
> 
> 对，就是那种短链接要如何处理呢？

3.7.0版本已加入原生支持
