### ISSUE TITLE
今天怎么出错了哦

### ISSUE THREAD

**Issue by walke2019** [qjfoidnh/BaiduPCS-Go#93]
获取目录下的文件列表: 网络错误, Get https://pcs.baidu.com/rest/2.0/pcs/file?app_id=266719&by=name&limit=0-2147483647&method=list&order=asc&path=%2F: read tcp 107.189.4.103:33822->140.249.34.53:443: read: connection reset by peer

**Comment by cinvro** [comment]
same here. 估计百度把PCS API 关了。

**Comment by qjfoidnh** [comment]
这两天有点事，等忙完我看一下

**Comment by joe12801** [comment]
同样的问题  Get https://pcs.baidu.com/rest/2.0/pcs/file?app_id=266719&by=name&limit=0-2147483647&method=list&order=asc&path=%2F: read tcp 144.172.118.211:37988->140.249.34.53:443: read: connection reset by peer

**Comment by xianbiao** [comment]
今天也出现了这个问题，经确认问题是出在 140.249.34.53 这个 IP ，可尝试通过修改系统 DNS 解决。但我换了好几个 DNS 依然被解析到这个有问题的 IP ，最后只好手动修改 hosts 文件，成功解决问题。

同样出现这个问题的可尝试在 hosts 文件加入以下任意一行，或其他可用 IP ：
119.167.143.63 pcs.baidu.com
111.206.209.9 pcs.baidu.com
36.152.44.22 pcs.baidu.com

希望有帮助~

**Comment by viviov** [comment]
> 今天也出现了这个问题，经确认问题是出在 140.249.34.53 这个 IP ，可尝试通过修改系统 DNS 解决。但我换了好几个 DNS 依然被解析到这个有问题的 IP ，最后只好手动修改 hosts 文件，成功解决问题。
> 
> 同样出现这个问题的可尝试在 hosts 文件加入以下任意一行，或其他可用 IP ：
> 119.167.143.63 pcs.baidu.com
> 111.206.209.9 pcs.baidu.com
> 36.152.44.22 pcs.baidu.com
> 
> 希望有帮助~

linux 下修改之后，ping显示是修改后的，PCS-go调用依然报错，报错的还是140的IP，是没生效么。。。。要如何生效呢

**Comment by joe12801** [comment]
按上面方法操作，真的管用，666，谢谢谢拉
