### ISSUE TITLE
以前没出现过的问题

### ISSUE THREAD

**Issue by walke2019** [qjfoidnh/BaiduPCS-Go#98]
今天运行时出现：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa pc=0x5daeb1]

goroutine 247 [running]:
net.(*Resolver).tryOneName(0x10a1920, 0xc231c0, 0xc00080eb80, 0xc0001a85a0, 0xc0008706a0, 0x15, 0x343066663761001c, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:254 +0x281
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0x10a1920, 0xc231c0, 0xc00080eb80, 0xc0001a85a0, 0xc0008706a0, 0x15, 0xc000878660, 0x1c)
        /usr/local/go/src/net/dnsclient_unix.go:602 +0x91
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:601 +0xd8

**Comment by qjfoidnh** [comment]
之前有人反映过类似问题，目前只知道跟主机的DNS设置有关，可以尝试换一个。
